### PR TITLE
BL-441 Bug/resources component rendering

### PR DESCRIPTION
**Pull request by daaavit**
## Description

/Resources component was not rendering due to a bug which was fixed.
added key props to resources cards and fixed warning

#### Video Link

https://www.loom.com/share/a09183119efe45bcb1f5a52350a0c9f5

https://loom.com/share/7290a5024e414b1ea59ba96e380c1f4d
#### Trello Link

https://trello.com/c/AllHe46N/416-resources-component-not-rendering

- [x] Bug fix (non-breaking change which fixes an issue)

## Checklist:

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have removed unnecessary comments/console logs from my code
- [x] My changes generate no new warnings
- [x] I have checked my code and corrected any misspellings
- [x] No duplicate code left within changed files
- [x] Size of pull request kept to a minimum
- [x] Pull request description clearly describes changes made & motivations for said changes

### CODE REVIEW

**Review by ChristOscar — APPROVED** [review]
Davvit thanks for fixing a bug that some of us weren't aware of. I reviewed the changes you made and everything seems to follow the structure that the team set. No problems are generated with adding this new code. Everything was clean and can be well maintained. 

The only issue I would say is, that you took two problems and made them into one pull request but that caused no issues. 

Great Work! 🔥

**Review by kcmercer — APPROVED** [review]
Everything looks good to me. Clean, concise and gets the job done. Good work.

**Review by JoshuaPattonWeb — APPROVED** [review]
Great additive. Straight to the point clean and constructive code. Nothing like a good old toggle to help people see what they typed if they forget. It's me, im people.

**Comment by daaavit** [comment]
[Resources component not rendering](https://trello.com/c/AllHe46N/416-resources-component-not-rendering)

**Pull request merged**
