### PR TITLE
deletes Admin folder along with all its contents, they are no longer …

### PR DESCRIPTION
**Pull request by ayv8er**
…being used in the app

## Description

Please include a summary of the change and which issue is fixed. Please also include relevant motivation and context. List any dependencies that are required for this change.

Fixes # (issue)

## Type of change

Please delete options that are not relevant.

- [X] Folder / File deletions, cleanup bloat

## Checklist:

- [X] My code follows the style guidelines of this project
- [X] I have performed a self-review of my own code
- [X] I have removed unnecessary comments/console logs from my code
- [ ] I have made corresponding changes to the documentation if necessary (optional)
- [X] My changes generate no new warnings
- [X] I have checked my code and corrected any misspellings
- [X] No duplicate code left within changed files
- [X] Size of pull request kept to a minimum
- [X] Pull request description clearly describes changes made & motivations for said changes

### CODE REVIEW

**Review by cyberkade — APPROVED** [review]
Thank you for clearing out more unused files!

**Review by rickmansfield — APPROVED** [review]
Nice to see all these removed. Thanks for doing for us.

**Review by teresafranxman97 — APPROVED** [review]
Clearing unnecessary files definitely helps in determining what components will be used in the application, thank you for taking the time to find and remove these.

**Review by rickmansfield — APPROVED** [review]
Thanks for eliminating unneeded files. Remember to add your Loom video and replace the description template sentence in the PR template.

**Review by Retrofitt — APPROVED** [review]
Always great seeing unused files being removed so that the overall clutter is cleared up, nice work!

**Comment by nhamilton1** [comment]
The cleaning up of the unused files is a beautiful site to see, very well done!

**Pull request merged**
