### PR TITLE
Fixed bug

### PR DESCRIPTION
**Pull request by kcmercer**
## Description

Deleted the useEffect within /src/components/pages/RoleSignup/Applications/Mentee.js and /src/components/pages/RoleSignup/Applications/Mentor.js that was unneeded because the user doesn't need to log in before they have an account created.

#### Video Link

https://www.loom.com/share/5ed2092bc5174299ae6ec70991dddfb4

#### Trello Link

https://trello.com/c/H3OAdPxv/384-bug-intake-form-makes-a-get-request-for-current-user-profile-before-the-user-has-a-profile

## Type of change

- [x] Bug fix (non-breaking change which fixes an issue).

## Checklist:

- [x] My code follows the style guidelines of this project.
- [x] I have performed a self-review of my own code.
- [x] I have removed unnecessary comments/console logs from my code.
- [x] My changes generate no new warnings.
- [x] I have checked my code and corrected any misspellings.
- [x] No duplicate code left within changed files.
- [x] Size of pull request kept to a minimum.
- [x] Pull request description clearly describes changes made & motivations for said changes.

### CODE REVIEW

**Review by gastonirby — DISMISSED** [review]
Good job spotting the issue, but it looks like we need to go a little further. You deleted the useEffect, but it's still being imported. This will cause the component to render with warnings. I think the import of useEffect needs to be removed as well.

**Review by leila-alhemali — CHANGES_REQUESTED** [review]
Same as Gaston -- need to remove  unnecessary imports.

The program still does a get request for the mentor/mentee on the application page. This is because the "sidebar" component (which renders on every page) does the get request also. It is a product design question. Are we okay with this unnecessary get request? Or do we need to change the design of the mentor/mentee intake forms to no longer render the "sidebar"?

**Review by leila-alhemali — APPROVED** [review]

**Review by ryanghoward — APPROVED** [review]
Nicely done

**Comment by MingjunGeng** [comment]
good work, I follow you to know how to push ticket

**Pull request merged**
