### PR TITLE
Features/Notes

### PR DESCRIPTION
**Pull request by areccus**
## Description

Added the notes component, form and styling.

[Trello](https://trello.com/c/OFcv8e79)

## Contributors: 
@areccus 
@prashishb 
@phillipgalbraith 

Fixes # (issue)

## Type of change

Please delete options that are not relevant.

- [X] New feature (non-breaking change which adds functionality)

## Checklist:

- [X] My code follows the style guidelines of this project
- [X] I have performed a self-review of my own code
- [X] I have removed unnecessary comments/console logs from my code
- [ ] I have made corresponding changes to the documentation if necessary (optional)
- [X] My changes generate no new warnings
- [X] I have checked my code and corrected any misspellings
- [X] No duplicate code left within changed files
- [X] Size of pull request kept to a minimum
- [X] Pull request description clearly describes changes made & motivations for said changes

### CODE REVIEW

**Review by itsmerobert12 — COMMENTED** [review]
Very nice job with this everyone! I was able to read correctly what is happening and the direction you are going! Rico, Phil, and Prashish keep up the good work!

**Review by jrosado184 — APPROVED** [review]

**Comment by jrosado184** [comment]
This feature is important for both mentee's and mentors, good job implementing this!

**Review by morgankj — APPROVED** [review]
Looks good! Clean code, looks dry and satisfies the task at hand! Well done

**Review by paulstgermain — CHANGES_REQUESTED** [review]
Thanks for leaving a link to the Trello card this PR is related to! That said, this PR's description still needs a video walkthrough where you talk about and showcase the changes made and explain why/how you made them before I can review and merge it up! 😱 

Let's get a video recorded and added to the description, and I'll circle back around to this PR then.

**Review by jcpcab — COMMENTED** [review]
Well done job guys! Very much needed/helpful note functionality !

**Pull request closed without merging**
