### PR TITLE
Style/applications

### PR DESCRIPTION
**Pull request by danielaescutia07**
## Description

https://www.loom.com/share/8bc880d0cf1a43adb32cc7c5e0e3a675

This PR is for updated styling implemented into Mentor and Mentee forms. After feedback was received, vertical forms was the best approach avoiding disruption the user's vertical momentum. Ant Design's Grid System was also implemented to allow responsiveness. Breathing room was also provided to the bottom portion of the forms to minimize clutter.

##Contributors
@danielaescutia07 @tristanharrower 

## Type of change

Please delete options that are not relevant.

- [x] New feature (non-breaking change which adds functionality)

## Checklist:

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have removed unnecessary comments/console logs from my code
- [x] I have made corresponding changes to the documentation if necessary (optional)
- [x] My changes generate no new warnings
- [x] I have checked my code and corrected any misspellings
- [x] No duplicate code left within changed files
- [x] Size of pull request kept to a minimum
- [x] Pull request description clearly describes changes made & motivations for said changes

### CODE REVIEW

**Review by tinaxgao — COMMENTED** [review]
Can you check what conflicts there are in the Mentee file?

**Review by tristanharrower — APPROVED** [review]
Code looks well organized and clean. GJ!

**Review by tinaxgao — APPROVED** [review]

**Review by djho57 — APPROVED** [review]
Style is pleasing to the eye! Good explanation video as well.

**Review by AnthonyMillerGit — COMMENTED** [review]
great work making this consistent with other form!

**Review by Fvaldenegro95 — APPROVED** [review]
Great explanation video!

**Comment by r-gio28** [comment]
Great changes using Ant design!

**Pull request merged**
