### PR TITLE
Refactor/front end tests

### PR DESCRIPTION
**Pull request by gastonirby**
## Description

This PR was co-authored by @minasoha 
Imported new redux.js/toolkit for the CreateTestStore and refactored the test store to be up to date
Changed the admin dashboard tests to auth0 from Okta
Added a function that works to allow window.matchMedia to run.

#### Video Link

https://www.loom.com/share/0404bd1fe6074fa19c0b338d512145f8

#### Trello Link

https://trello.com/c/9ylNLlFT/374-fix-front-end-tests

## Type of change

___Please delete options that are not relevant.___

- [X] Bug fix (non-breaking change which fixes an issue)

## Checklist:

- [X] My code follows the style guidelines of this project
- [X] I have performed a self-review of my own code
- [X] I have removed unnecessary comments/console logs from my code
- [X] My changes generate no new warnings
- [X] I have checked my code and corrected any misspellings
- [X] No duplicate code left within changed files
- [X] Size of pull request kept to a minimum
- [X] Pull request description clearly describes changes made & motivations for said changes

### CODE REVIEW

**Review by ryanghoward — APPROVED** [review]
Nicely done! Great find with using configureStore as a work around to refactor these tests.

**Review by FftyShadesofCode — APPROVED** [review]
You guys worked hard on this. Great job! It looks great!

**Comment by MingjunGeng** [comment]
Fantastic work!

**Review by minasoha — APPROVED** [review]
Great job figuring out the workaround for the matchMedia!

**Review by andrejohnson — APPROVED** [review]
testing has always been where I'm lacking the most, makes me happy to see someone hit the ground running with it good job

**Pull request merged**
