### PR TITLE
notfoundgame added to 404 page

### PR DESCRIPTION
**Pull request by JoeyBertschler**
## Description

Converted 404 jump-and-run not found game into a React component and added it as such to the corresponding 404 page. It uses a combination of CSS styles and state variables.

#### Video Link

https://www.loom.com/share/ebdf882e76304782abdc576dcb8e83a5

#### Trello Link

[___Paste your trello card link here, deleting this example___](https://trello.com/c/zag5yLS4/376-refactor-js-code-into-react-component-and-add-to-404-page)

## Type of change

- [x] New feature (non-breaking change which adds functionality)

## Checklist:

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have removed unnecessary comments/console logs from my code
- [x] My changes generate no new warnings
- [x] I have checked my code and corrected any misspellings
- [x] No duplicate code left within changed files
- [x] Size of pull request kept to a minimum
- [x] Pull request description clearly describes changes made & motivations for said changes

NOTE: At the time of writing, this, Dialog.js (components/common/DialogButton) is broken (has nothing to do with me, but noticed it during localhost based testing of the component). See Loom video for details.

### CODE REVIEW

**Review by oscy7 — APPROVED** [review]
Nice work on the game! Having a little fun in the event of a 404 gives the app great character!

**Review by VABIII — APPROVED** [review]
Nice job with the animations and stylings

**Review by quawilburn — APPROVED** [review]
This is a very cool feature to have. Nice work getting it implemented.

**Review by minasoha — APPROVED** [review]
Great job figuring out the animation for the game.

**Review by khaleel737 — APPROVED** [review]
Great job with the animation and styling, nicely done

**Review by malloryshea — APPROVED** [review]
Nice catch all! Great job with the styling as well.

**Pull request closed without merging**
