### PR TITLE
Removed email section and additional styles

### PR DESCRIPTION
**Pull request by robstetson**
## Description

Due to the implementation of the review application functionality, the email column is now obsolete. Removing said column and any additional styling to make sure code stays "DRY" and clean.

#### Video Link

[Loom Video] https://www.loom.com/share/e1668e85ea794609813c6210c5597636

#### Trello Link

https://trello.com/c/zBUIkVPc

## Type of change

___Please delete options that are not relevant.___

- [X] Bug fix (non-breaking change which fixes an issue)

## Checklist:

- [X] My code follows the style guidelines of this project
- [X] I have performed a self-review of my own code
- [X] I have removed unnecessary comments/console logs from my code
- [X] My changes generate no new warnings
- [X] I have checked my code and corrected any misspellings
- [X] No duplicate code left within changed files
- [X] Size of pull request kept to a minimum
- [X] Pull request description clearly describes changes made & motivations for said changes

### CODE REVIEW

**Review by WaylayOvercast — APPROVED** [review]
looks like a simple but effective fix, good work.

**Review by NPAPENBURG — APPROVED** [review]
Simple, but great change! Good stuff!

**Review by yefim-g — APPROVED** [review]
Simple fix, but definitely helps the code stay within the guidelines of 'DRY'.

**Review by jonathan-mcgraw — APPROVED** [review]
Good job, sir. Thank you for helping take care of this so quickly.

**Pull request merged**
