### PR TITLE
BL-460 Bug/mentor mentee add reviews

### PR DESCRIPTION
**Pull request by daaavit**
## Description

mentor/mentee can add reviews

#### Video Link

https://www.loom.com/share/358ba21d622142d7a7c7e32784d7e0fe

#### Trello Link

(https://trello.com/c/2iSFBqa8/417-mentor-mentee-cant-add-reviews)

(Example below):

## Type of change

- [x] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)

## Checklist:

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have removed unnecessary comments/console logs from my code
- [x] My changes generate no new warnings
- [x] I have checked my code and corrected any misspellings
- [x] No duplicate code left within changed files
- [x] Size of pull request kept to a minimum
- [x] Pull request description clearly describes changes made & motivations for said changes

### CODE REVIEW

**Review by roxanneweber — APPROVED** [review]
Code is clean and fixed the bug. Great work!

**Review by DatBoiLuiskrrt — APPROVED** [review]
Looks great to me!

**Review by joseph-fantuzzi — APPROVED** [review]
Great job again @daaavit! The loom video shows what should be implemented and your process of solving it. Both mentors and mentees should be able to leave reviews, so good idea giving mentees the ability to write reviews as well. Good job!

**Review by ethanrmiles — APPROVED** [review]
Great code, great video.

**Pull request merged**
