### PR TITLE
removes merged merge conflict messages from package-lock.json

### PR DESCRIPTION
**Pull request by paulstgermain**
## Description

This PR fixes a production-stopping error in our `package-lock` file by removing some merge conflict resolution messages that somehow made it into main.

### Fixes

This fixes our deployment, allowing us to keep production up-to-date with main again.

## Type of change

Please delete options that are not relevant.

- [x] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [x] This change requires a documentation update

## Checklist:

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have removed unnecessary comments/console logs from my code
- [x] I have made corresponding changes to the documentation if necessary (optional)
- [x] My changes generate no new warnings
- [x] I have checked my code and corrected any misspellings
- [x] No duplicate code left within changed files
- [x] Size of pull request kept to a minimum
- [x] Pull request description clearly describes changes made & motivations for said changes

### CODE REVIEW

**Review by jessejohns-1 — APPROVED** [review]
Amazing work, finding this error so we can deploy is absolutely detrimental truly inspiring work paul bravo.

**Review by TrevourGuild — APPROVED** [review]
Great job at fixing this! Now we can deploy to the official site!

**Review by kennymiesner — APPROVED** [review]
Thanks for fixing this!

**Review by taylorkangillescas — COMMENTED** [review]
Thanks for finding and fixing this!

**Comment by johanna-rodriguez** [comment]
Thank you so much for fixing the error. Awesome!

**Pull request merged**
