### PR TITLE
BL-302 fixing mentee intake application endpoint

### PR DESCRIPTION
**Pull request by wenjuncai97**
## Description

-- fixed bug that wasn't allowing mentees/mentors applications to post to our BE severs. Updated relevant fields to their actual values in-line with DS API 0.48.0. Submitted forms weren't intaking the correct values for 'other_info' and 'convictions',  changes reflect the application submitting with the correct values.

Fixes # (689)

[## Loom Video](https://www.loom.com/share/09848a75f7394a9e8c26ad159b2745d6)

Jira Board Link

https://bloomtechlabs.atlassian.net/browse/BL-689

## Type of change

- [x] Bug fix (non-breaking change which fixes an issue)

## Checklist:

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have removed unnecessary comments/console logs from my code
- [x] I have made corresponding changes to the documentation if necessary (optional)
- [x] My changes generate no new warnings
- [x] I have checked my code and corrected any misspellings
- [x] No duplicate code left within changed files
- [x] Size of pull request kept to a minimum
- [x] Pull request description clearly describes changes made & motivations for said changes

### CODE REVIEW

**Review by ezra-casas — APPROVED** [review]
Good code clean up. And better code format. Keep it up!

**Review by jettyblue — APPROVED** [review]
Nice work here, code looks great. Good job identifying the issue of the form input being in the wrong area and implementing a fix to get a working output.

**Comment by jack-semder** [comment]
Great bug fix, allowing mentors/mentees to access BE is a great feat!

**Comment by woodbenwood** [comment]
What a win -- this work is a triumph. I specifically found the referred_by and heard_about stuff very interesting!

**Review by zdravoj — APPROVED** [review]
Nicely done. Payload at end of loom video lines up nicely with the MongoDB Mentee schema. Great work!

**Pull request merged**
