### PR TITLE
adds skeleton loading to the dashboard

### PR DESCRIPTION
**Pull request by nhamilton1**
## Description

This will show the user where they will expect to see content that will show up on the page resulting in a smooth loading screen.

## Type of change

- [x] New feature (non-breaking change which adds functionality)

## Checklist:

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have removed unnecessary comments/console logs from my code
- [x] I have made corresponding changes to the documentation if necessary (optional)
- [x] My changes generate no new warnings
- [x] I have checked my code and corrected any misspellings
- [x] No duplicate code left within changed files
- [x] Size of pull request kept to a minimum
- [x] Pull request description clearly describes changes made & motivations for said changes

https://www.loom.com/share/c7ebb7bb4b82422aac2d5b6dd5ba1c77

### CODE REVIEW

**Review by Chris-Boyle-94 — APPROVED** [review]
This is awesome, this looks a lot better than just seeing a message letting the user know that information is still loading

**Review by rickmansfield — APPROVED** [review]
Again a pro look that polishes the project. Thanks for adding this code.

**Review by Tereamarie — APPROVED** [review]
Great Loom video very nice not scrolling too fast easy to see what changes you made. Nice Job

**Review by Retrofitt — APPROVED** [review]
You're loom video was a great walkthrough of the code you implemented and the actual design on the app looks great! Good work!

**Review by ayv8er — APPROVED** [review]
I didn't know Ant Design had this, I love it!

**Review by Pluviio — APPROVED** [review]
I think adding this feature makes the site look really professional and from a users stand point is just nice to look at. Looks amazing

**Pull request merged**
