### PR TITLE
Bl 800 clicking on the ud logo on the signup page leaves the entire viewport blank

### PR DESCRIPTION
**Pull request by andrewgomez1992**
## Description

We created a function (reloadLogo) to check if user is authenticated or not. If you are not logged in and you click on logo, the login page will refresh. If you are logged in and you click on logo, it will take you to the dashboard.  We also changed the container of UD logo from Link to div because of pathname conflictions. Added cursor pointer to logo img to show that it is clickable. 

Fixes # (BL-800)

## Loom Video

(https://loom.com/share/f03a15693c6a4b32a460705dc5baa3c5)

## Type of change

Please delete options that are not relevant.

- [ ✔️] Bug fix (non-breaking change which fixes an issue)

## Checklist:

- [ ✔️] My code follows the style guidelines of this project
- [ ✔️] I have performed a self-review of my own code
- [ ✔️] I have removed unnecessary comments/console logs from my code
- [ ✔️] I have made corresponding changes to the documentation if necessary (optional)
- [ ✔️] My changes generate no new warnings
- [ ✔️] I have checked my code and corrected any misspellings
- [ ✔️] No duplicate code left within changed files
- [ ✔️] Size of pull request kept to a minimum
- [ ✔️] Pull request description clearly describes changes made & motivations for said changes

## Assignees
@AndrewGomez @Maximilian

### CODE REVIEW

**Review by nathancai97 — APPROVED** [review]
Great implementation of logic and code! The cursor pointer is a great touch for user experience.

**Review by miguelaledesma — APPROVED** [review]
Clean implementation, i like that you added the cursor pointer style in the css and not inline since it will be easier to find in the future. Simple fix. Also nice and clean implementation of the reload logo function, super easy to know what its doing . great job.

**Review by jettyblue — APPROVED** [review]
Excellent work! Love the inclusion of a cursor pointer for clickable items. Nicely done

**Review by khaleel737 — APPROVED** [review]
Great work on the logo, clean implementation and code base.

**Comment by albert-szabo** [comment]
This is a helpful, effective improvement! The concise ternary is clear and easy to understand.

**Review by albert-szabo — APPROVED** [review]
This is a helpful, effective improvement! The concise ternary is clear and easy to understand.

**Review by stevenhastings — COMMENTED** [review]
Even with the tests failing; I really like this small, yet important change. It's keeping the user in the pocket and, the focus on the task that is needed to be performed.

**Comment by brimjustin** [comment]
The changes made give the page a much better look and feel of completeness!

**Review by brimjustin — COMMENTED** [review]
The changes made give the page a much better look and feel of completeness!

**Pull request merged**
