### PR TITLE
Added endpoints for mentor/mentee

### PR DESCRIPTION
**Pull request by iwood55**
## Description

Added the endpoints for mentors and mentees to create new accounts.

## Type of change

Please delete options that are not relevant.

- [x] New feature (non-breaking change which adds functionality)

## Checklist:

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have removed unnecessary comments/console logs from my code
- [x] I have made corresponding changes to the documentation if necessary (optional)
- [x] My changes generate no new warnings
- [x] I have checked my code and corrected any misspellings
- [x] No duplicate code left within changed files
- [x] Size of pull request kept to a minimum
- [x] Pull request description clearly describes changes made & motivations for said changes

https://user-images.githubusercontent.com/81526595/142504010-e60420f6-6ab8-45ad-89d2-1f54c23bfb6f.mp4

### CODE REVIEW

**Review by Broveku — APPROVED** [review]
nice job getting this component finished off with the endpoints. endpoints look good.

**Comment by johanna-rodriguez** [comment]
Great job adding the endpoints. It's look very nice.

**Comment by rickmansfield** [comment]
Perfect. Brief to the point and certainly needed. Let's get this merged

**Comment by ayv8er** [comment]
Endpoints tested and returns!

**Review by rickmansfield — APPROVED** [review]
Lett get this merged

**Comment by nhamilton1** [comment]
Looks good, ready to add this!

**Comment by Retrofitt** [comment]
Fantastic work setting up the endpoints, looks good to merge.

**Review by Retrofitt — APPROVED** [review]
## Video Feedback
Nice, Short, Straight to the point

## Code Feedback
Fantastic work setting up the endpoints, looks good to merge.

**Pull request merged**
