### PR TITLE
Notes Styling Changes

### PR DESCRIPTION
**Pull request by prashishb**
## Description

As a user, I want to know what each Notes table and form item represents by its label/description/color/icon to create/edit/reply to notes easily and intuitively.

Additions:

- Status icons / colors

Changes:

- Removed visibility column and checklist (visibility will be implied by subject)
- Removed flags for subject and status to reduce clutter
- Added icons for the select element's options on the Add Note form
- Added colored icons for the subject column
- Moved in-line stylings to its own `.css` file
- Changed labels in `NotesForm` to keep it consistent with Notes table
- Submit and Save Draft button now uses Primary / Secondary ant design styles in `NotesForm`

Trello <a href="https://trello.com/c/lDFkTjBT" target="_blank">#275</a>
[Loom Walkthrough](https://www.loom.com/share/f6c24b4231974a79af525aa7a9986f19)

## Contributors
@prashishb
@phillipgalbraith 

## Type of change

- [X] New feature (non-breaking change which adds functionality)

## Checklist:

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [X] I have removed unnecessary comments/console logs from my code
- [X] My changes generate no new warnings
- [x] I have checked my code and corrected any misspellings
- [x] No duplicate code left within changed files
- [x] Size of pull request kept to a minimum
- [x] Pull request description clearly describes changes made & motivations for said changes

### CODE REVIEW

**Review by arsalan2243 — APPROVED** [review]
Great job. that's tons of work to be by one person.  now the only thing left is to fix that merge conflict and it will be good to go.

**Review by jrosado184 — APPROVED** [review]
Changes look better and organized, the code structure also looks like it was improved. Good job!

**Review by maidiance — APPROVED** [review]
Absolutely improved over the pill box design. This is much more user friendly, great work!

**Review by areccus — APPROVED** [review]
This is the one. I love this styling, I don't which one of y'all came up with this, but sheesh.

**Pull request merged**
