### PR TITLE
Feature/update profile form

### PR DESCRIPTION
**Pull request by RaphaelHebert**
## Description

Please include a summary of the change and which issue is fixed. Please also include relevant motivation and context. List any dependencies that are required for this change.

Fixes # (issue)

## Type of change

Please delete options that are not relevant.

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] This change requires a documentation update

## Checklist:

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have removed unnecessary comments/console logs from my code
- [x] I have made corresponding changes to the documentation if necessary (optional)
- [x] My changes generate no new warnings
- [x] I have checked my code and corrected any misspellings
- [x] No duplicate code left within changed files
- [x] Size of pull request kept to a minimum
- [x] Pull request description clearly describes changes made & motivations for said changes

### CODE REVIEW

**Comment by RaphaelHebert** [comment]
Refactored forms of the update-profile components:
- added a spinner while loading the profile list
- deleted yup validation form
- made form fully functionnal

**Review by Broveku — COMMENTED** [review]
updated profile form looks good, really like the spinner you added to let the user know information is loading

**Review by JorshuaG — CHANGES_REQUESTED** [review]
Forms look good, but some of the information key:values are a bit off from the back end tables. the user profile doesnt have a "role_name" in the DB so this key is not needed. The "role_id" is the foreign key that represents the role_name associated in a different table. Also, the "approved" Boolean value is named "pending" and "user_id" in the backend is named "profile_id" We would need to update these before merging otherwise the DB wont be able to accept the data properly.

**Comment by johanna-rodriguez** [comment]
The spinner and the profile form looks great.

**Comment by RaphaelHebert** [comment]
> Forms look good, but some of the information key:values are a bit off from the back end tables. the user profile doesnt have a "role_name" in the DB so this key is not needed. The "role_id" is the foreign key that represents the role_name associated in a different table. Also, the "approved" Boolean value is named "pending" and "user_id" in the backend is named "profile_id" We would need to update these before merging otherwise the DB wont be able to accept the data properly.

Ok, good to know, I just took the profile schema available in the readme of the backend repo which gives the following user schema as exemple: {
    "user_id": "00ulzfj6nX72gu3Nh4d6",
    "email": "email@email.mail",
    "first_name":"John",
    "last_name":"Doe",
    "role_id": 3,
    "role_name": "user",
    "created_at": "2021-04-21T18:47:18.712Z",
    "updated_at": "2021-04-21T18:47:18.712Z",
    "approved": True
}

**Review by ChristopherHenao — APPROVED** [review]
I like the spinner you added.

**Review by JorshuaG — APPROVED** [review]
Updated changes look great

**Review by paulstgermain — CHANGES_REQUESTED** [review]
You seem to have left out a Loom recording explaining the changes made in this PR - please do so before I merge this PR!

**Review by taylorkangillescas — APPROVED** [review]
Great job updating the suggested changes. Looks good.

**Review by iwood55 — APPROVED** [review]
Changes look great and you articulated them well in the meeting yesterday as well as the loom video!

**Review by paulstgermain — APPROVED** [review]

**Pull request merged**
