### PR TITLE
Schedule dialog

### PR DESCRIPTION
**Pull request by JoshuaPattonWeb**
## Description

Constructed UI for scheduling/requesting to meet with a mentor.
Added filler values for mentors along with date and time for scheduled meetings.
Created success notification upon scheduling your meeting.

#### Video Link

https://www.loom.com/share/0adfd5a6e10c4b8f94cfd7a39754b457

#### Trello Link

<blockquote class="trello-card"><a href="https:&#x2F;&#x2F;trello.com&#x2F;c&#x2F;c2cfGNfx&#x2F;241-as-a-user-i-want-to-be-able-to-schedule-a-meeting">As a user, I want to be able to schedule a meeting</a></blockquote><script src="https://p.trellocdn.com/embed.min.js"></script>

## Type of change

___Please delete options that are not relevant.___

- [x] New feature (non-breaking change which adds functionality)
- [x] This change requires a documentation update

## Checklist:

- [x ] My code follows the style guidelines of this project
- [x ] I have performed a self-review of my own code
- [x ] I have removed unnecessary comments/console logs from my code
- [x ] My changes generate no new warnings
- [x ] I have checked my code and corrected any misspellings
- [x ] No duplicate code left within changed files
- [x ] Size of pull request kept to a minimum
- [x ] Pull request description clearly describes changes made & motivations for said changes

### CODE REVIEW

**Comment by xokeixo** [comment]
This looks amazing!!! I feel as though it should be one calendar as well, but what you have is great to me.

**Review by xokeixo — APPROVED** [review]
Great work on the calendar.

**Review by sebas6292 — APPROVED** [review]
clean code and way to incorporate antd design in the components and updating the state.

**Review by VABIII — APPROVED** [review]
Code looks clean and concise. Well done.

**Pull request merged**
