### PR TITLE
Feature/Routing Refactor 3

### PR DESCRIPTION
**Pull request by MrJacobSullivan**
## Description

In this PR, we finalized the routing refactor. We reworked the `Sidebar` component to `push` to the desired route as opposed to changing what component is being rendered within the sidebar. We deleted the `SidebarComponents` file as well as the `HomeContainer` file as those were both only necessary when we were having the `Sidebar` handle rendering. We also cleaned up a few of the functions within the `Sidebar` component to be less verbose. We were also careful to delete any imports that were no longer needed.

Trello [#228](https://trello.com/c/qZDddrBi)
[Loom Walkthrough](https://www.loom.com/share/5e589407eecd4b1abc9f0bd30fbd5ba6)

## Contributors
@MrJacobSullivan 
@Fvaldenegro95 
@r-gio28 

## Type of change

Please delete options that are not relevant.

- [x] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)

## Checklist:

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have removed unnecessary comments/console logs from my code
- [x] My changes generate no new warnings
- [x] I have checked my code and corrected any misspellings
- [x] No duplicate code left within changed files
- [x] Size of pull request kept to a minimum
- [x] Pull request description clearly describes changes made & motivations for said changes

### CODE REVIEW

**Review by ErikBahena — APPROVED** [review]
Great job cleaning up the unnecessary imports. Nifty work with the pushing of a menu key.

**Review by ryansnorek — APPROVED** [review]
Very sexy code! My favorite is the path name keys

**Review by rdperry031 — APPROVED** [review]
This is nice and clean. Pushing to the actual component is definitely the way to go as well. Good work.

**Review by Jaredhall18 — APPROVED** [review]
Changes look great. This routing refactor was a massive undertaking, awesome job Jacob.

**Pull request merged**
