### PR TITLE
BL-801-cleanup-sign-up-page

### PR DESCRIPTION
**Pull request by nathancai97**
## Description

-- Fixed layout for the apply/sign up page by removing unnecessary white space, changed button texts, and added 5 new media queries corresponding to google chrome's inspect page device dimensions. As a result, all the different devices now have a uniform layout. 

Fixes # (https://bloomtechlabs.atlassian.net/browse/BL-801)

## Loom Video

(https://www.loom.com/share/0398e1aae59b4842b14cc019784125cf)

## Type of change

- [x] Bug fix (non-breaking change which fixes an issue)

## Checklist:

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have removed unnecessary comments/console logs from my code
- [x] I have made corresponding changes to the documentation if necessary (optional)
- [x] My changes generate no new warnings
- [x] I have checked my code and corrected any misspellings
- [x] No duplicate code left within changed files
- [x] Size of pull request kept to a minimum
- [x] Pull request description clearly describes changes made & motivations for said changes

### CODE REVIEW

**Review by miguelaledesma — DISMISSED** [review]
This PR is really clean. Kept to a minimum in commit count and no unnecessary code/console logs. Nice touch adding media queries to handle different screen sizes. It's sometimes overlooked and I am happy to see you took the extra time to implement that. I do not see anything that needs to be revisited. Great job Nathan!!!!

**Review by miguelaledesma — APPROVED** [review]
Re-reviewing, seems you added same text to the mentee app to match mentor. Good catch. I stand by my initial review. :)

**Review by stevenhastings — COMMENTED** [review]
thorough cleaning, well done!

**Review by stevenhastings — APPROVED** [review]
stamp of approval

**Review by Rlauckern — APPROVED** [review]
Nice cleanup. Way more tidy and organized!

**Review by zdravoj — APPROVED** [review]
Nice job implementing these changes at different sizes. It's great to have support for a variety of screen sizes!

**Review by khaleel737 — APPROVED** [review]
Much more organized and clean, great work making the codebase readable and easier to navigate

**Comment by brimjustin** [comment]
The sign up page is much more organized than before. Great job!

**Pull request merged**
