### PR TITLE
Features/readme/profiles

### PR DESCRIPTION
**Pull request by tfbielawski**
## Description

Updated the existing README code by adding team members' GitHub profiles, avatars, and team assignments

Fixes # (issue)

## Type of change

Please delete options that are not relevant.

- [x] New feature (non-breaking change which adds functionality)

## Checklist:

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have removed unnecessary comments/console logs from my code
- [x] I have made corresponding changes to the documentation if necessary (optional)
- [x] My changes generate no new warnings
- [x] I have checked my code and corrected any misspellings
- [x] No duplicate code left within changed files
- [x] Size of pull request kept to a minimum
- [x] Pull request description clearly describes changes made & motiv

https://user-images.githubusercontent.com/70349084/141841296-66f19d30-7b18-4809-98d6-bcc4e3522d98.mp4

ations for said changes

### CODE REVIEW

**Review by JorshuaG — APPROVED** [review]
Looks great, nice having all contributors being recognized. Great job

**Comment by johanna-rodriguez** [comment]
Awesome work.

**Review by taylorkangillescas — APPROVED** [review]
Great job adding team roles, profiles, and avatars. Looks very clean and professional.

**Review by mariuscmoldovan — APPROVED** [review]
Nice job in updating the team profile and roles to the readme file.

**Review by Broveku — COMMENTED** [review]
This is a really great way to help future devs maintain vision and clarity with the code base, great addition.

**Pull request merged**
