### PR TITLE
manipulated details input to accept styling, allow for word wrapping …

### PR DESCRIPTION
**Pull request by JoshuaPattonWeb**
…and also having the cursor start that the proper placement.

## Description

Converted the details input to a textArea which automatically implemented word wrapping along with proper cursor placement. We then altered the color of text and background as the text was defaulted to white.

#### Video Link

(https://www.loom.com/share/b6c01770e02d4ee18a544d0f76fe3bb0)

#### Trello Link

___Paste your trello card link here, deleting this example___

<blockquote class="trello-card"><a href="https:&#x2F;&#x2F;trello.com&#x2F;c&#x2F;c2cfGNfx&#x2F;241-as-a-user-i-want-to-be-able-to-schedule-a-meeting">As a user, I want to be able to schedule a meeting</a></blockquote><script src="https://p.trellocdn.com/embed.min.js"></script>

## Type of change

___Please delete options that are not relevant.___

- [x] Bug fix (non-breaking change which fixes an issue)

## Checklist:

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have removed unnecessary comments/console logs from my code
- [x] My changes generate no new warnings
- [x] I have checked my code and corrected any misspellings
- [x] No duplicate code left within changed files
- [x} Size of pull request kept to a minimum
- [x} Pull request description clearly describes changes made & motivations for said changes

### CODE REVIEW

**Review by AkhilP423 — APPROVED** [review]
Everything looks good, perhaps review the formatting for the css file to make it more readable. However it seems fine as is!

**Comment by JoeyBertschler** [comment]
Love the extra context from the Loom video, which I believe tends to be underestimated in value. Very clean approach (e.g. deleting unused imports), kudos!

**Review by gastonirby — COMMENTED** [review]
I'm new to this, reviewing, but it looks like it's being pushed with warnings. Shouldn't those be handled before pushing?

**Review by gastonirby — APPROVED** [review]
Good job noticing the small details and implementing changes accordingly!

**Review by ryanghoward — APPROVED** [review]
Looks great! Great job on finding a solution.

**Review by JoeyBertschler — COMMENTED** [review]
Love the extra context from the Loom video, which I believe tends to be underestimated in value. Very clean approach (e.g. deleting unused imports), kudos!

**Pull request merged**
