### PR TITLE
navbar axios call fixed

### PR DESCRIPTION
**Pull request by maidiance**
## Description

Through some debugging, found out that my navbar axios call is incorrect. This PR is fixing that issue.
As a quick note, [Sheeba](https://github.com/sheebaHashmi) helped me fix my index.js.

#### Video Link

[Loom Video](https://www.loom.com/share/81ecd94cb2ec4795b4981e98b0c40cee)

#### Trello Link

<blockquote class="trello-card"><a href="https://trello.com/c/gfkGi9lY/296-navbar-axios-call-fix">Fix: Navbar axios call</a></blockquote>

## Type of change

- [✔️] Bug fix (non-breaking change which fixes an issue)

## Checklist:

- [✔️] My code follows the style guidelines of this project
- [✔️] I have performed a self-review of my own code
- [✔️] I have removed unnecessary comments/console logs from my code
- [✔️] My changes generate no new warnings
- [✔️] I have checked my code and corrected any misspellings
- [✔️] No duplicate code left within changed files
- [✔️] Size of pull request kept to a minimum
- [✔️] Pull request description clearly describes changes made & motivations for said changes

### CODE REVIEW

**Review by arsalan2243 — APPROVED** [review]
good job!
i had the same type of issue too.
i am glad that you were able to fix this issue. making that loom video will certainly help to increase the speed of bug fixing for the next group.

**Review by acoman-cloud — APPROVED** [review]
Looks like simple and clean, dry code that fixes a problem.

**Review by areccus — APPROVED** [review]
You and Sheeba may be the dynamic duo. Thanks for fixing this.

**Review by ryan-hamblin — APPROVED** [review]
This is super straightforward. Merging.

**Comment by ryan-hamblin** [comment]
@maidiance I cannot merge until merge conflicts are resolved. Must've had someone get a merge in between this one! :) LMK when you resolve the conflicts.

**Comment by maidiance** [comment]
> Why is isAuthenticated still in this file? It seems like it could be cleaned up a little. Otherwise this pull request is an important bug fix that I look forward to having implemented. Thanks!

Can you explain this? I don't mind making another pull request to target the change you'd like to see.

**Comment by maidiance** [comment]
> @maidiance I cannot merge until merge conflicts are resolved. Must've had someone get a merge in between this one! :) LMK when you resolve the conflicts.

The conflict looks resolved to me now, please double check to make sure. Thank you!

**Pull request merged**
