### PR TITLE
Bug/Sidebar minimization

### PR DESCRIPTION
**Pull request by maidiance**
## Description

Swapnali asked for the drawer controller to disappear for mobile, instead simply forcing the sidebar to be default collapsed on mobile.

#### Video Link

[Loom Video](https://www.loom.com/share/f937676763394bba80d3cc5b7c1ea22f)

#### Trello Link

<blockquote class="trello-card"><a href="https://trello.com/c/Tu4JKBVc/297-as-a-user-i-should-have-a-minimized-version-of-the-sidebar-in-mobile-view">As a user, I should have a minimized version of the sidebar in mobile view</a></blockquote>

## Type of change

- [✔️] Bug fix (non-breaking change which fixes an issue)

## Checklist:

- [✔️] My code follows the style guidelines of this project
- [✔️] I have performed a self-review of my own code
- [✔️] I have removed unnecessary comments/console logs from my code
- [✔️] My changes generate no new warnings
- [✔️] I have checked my code and corrected any misspellings
- [✔️] No duplicate code left within changed files
- [✔️] Size of pull request kept to a minimum
- [✔️] Pull request description clearly describes changes made & motivations for said changes

### CODE REVIEW

**Review by Arison13 — APPROVED** [review]
This all seems like a really clean and short PR, the only thing is you should probably remove the unused functions or components to avoid any warnings. But overall really good work!

**Comment by maidiance** [comment]
> This all seems like a really clean and short PR, the only thing is you should probably remove the unused functions or components to avoid any warnings. But overall really good work!

Good call, I will do this!

**Review by ChristianSmith2394 — APPROVED** [review]
Great work!

**Review by arsalan2243 — APPROVED** [review]
this fix helps the drawer control to have a smoother transition instead of sudden collapse.
good work.

**Pull request merged**
