### PR TITLE
added matching page wireframes

### PR DESCRIPTION
**Pull request by tarasshulhan**
## Description

Added wireframes of the matching feature

Fixes # (issue)

## Type of change

Please delete options that are not relevant.

- [ ] New feature (non-breaking change which adds functionality)

## Checklist:

- [ ] My code follows the style guidelines of this project
- [ ] I have performed a self-review of my own code
- [ ] I have removed unnecessary comments/console logs from my code
- [ ] I have made corresponding changes to the documentation if necessary (optional)
- [ ] My changes generate no new warnings
- [ ] I have checked my code and corrected any misspellings
- [ ] No duplicate code left within changed files
- [ ] Size of pull request kept to a minimum
- [ ] Pull request description clearly describes changes made & motivations for said changes

### CODE REVIEW

**Review by bbellify — APPROVED** [review]
These look awesome, nicely done keeping design/wireframes updated 👍

**Review by danielaescutia07 — APPROVED** [review]
Great way to keep wireframe updated!

**Review by Fvaldenegro95 — APPROVED** [review]
Very accessible and clean! Nice!

**Review by rdperry031 — APPROVED** [review]
These look great. It's good to have some updated wireframes.

**Review by djho57 — APPROVED** [review]
Design is clean and efficient!

**Review by ChristineWangcy — APPROVED** [review]
It looks great and clean!

**Pull request merged**
