### PR TITLE
Removed highlighting around input buttons

### PR DESCRIPTION
**Pull request by prashishb**
## Description

Bug fix to remove highlighting around input buttons globally as discussed in Design Critiques with Swapnali.

#### Video Link

[Loom Video](https://www.loom.com/share/37bd89acaca046e7bddc44bd3276728e)

#### Trello Link

<blockquote class="trello-card"><a href="https:&#x2F;&#x2F;trello.com&#x2F;c&#x2F;71PyCMDA&#x2F;309-bug-remove-yellow-highlighting-on-input-buttons">bug- remove yellow highlighting on input buttons</a></blockquote>

## Type of change

___Please delete options that are not relevant.___

- [X] Bug fix (non-breaking change which fixes an issue)

## Checklist:

- [X] My code follows the style guidelines of this project
- [X] I have performed a self-review of my own code
- [X] I have removed unnecessary comments/console logs from my code
- [X] My changes generate no new warnings
- [X] I have checked my code and corrected any misspellings
- [X] No duplicate code left within changed files
- [X] Size of pull request kept to a minimum
- [X] Pull request description clearly describes changes made & motivations for said changes

### CODE REVIEW

**Review by maidiance — APPROVED** [review]
A very necessary change. Looks very clean and well done.

**Review by BrittniKarat — APPROVED** [review]
Quick fix and I think it looks way better without the yellow. Thank you for taking Swapnali's feedback and quickly resolving it.

**Review by acoman-cloud — APPROVED** [review]
Looks good and video was clear and succinct.

**Review by wscottreynders — APPROVED** [review]
Looks great this way. Good implementation.

**Pull request merged**
