### PR TITLE
Bug/route cleanup

### PR DESCRIPTION
**Pull request by cyberkade**
## Description

There are some remaining boilerplate templates as well as unnecessary routes and folders that clog up the codebase, potentially causing problems. This PR cleans up those unused folders and routes, as well as ensuring the correct routes are secure, resulting in the intended login experience.

## Type of change

- [x] Bug fix (non-breaking change which fixes an issue)

## Checklist:

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have removed unnecessary comments/console logs from my code
- [x] My changes generate no new warnings
- [x] I have checked my code and corrected any misspellings
- [x] No duplicate code left within changed files
- [x] Size of pull request kept to a minimum
- [x] Pull request description clearly describes changes made & motivations for said changes

## Loom Video

https://www.loom.com/share/0ab91b2dd36842e99689a537bef28a86

### CODE REVIEW

**Review by Chris-Boyle-94 — APPROVED** [review]
Removing the unused code makes things a lot less cluttered

**Review by nhamilton1 — APPROVED** [review]
Love the cleanup, helps a lot with navigation through the code!

**Review by Retrofitt — APPROVED** [review]
Great job cleaning up the unused routes and files. Makes the code a bit less overwhelming and readable.

**Review by rickmansfield — APPROVED** [review]
Much better to have some unused code out of the way. Much more pro-looking code. Thanks

**Review by Tereamarie — APPROVED** [review]
Great video description of your changes and cleanup of the code. Repeat code is not good great job

**Review by Pluviio — APPROVED** [review]
As someone who hasn't really looked at front end too much till now to check on progress the routes clean up was done really well. Makes it clear to read and I know exactly whats being done

**Pull request merged**
