### PR TITLE
Bl 864 web transition from sign up to apply flow

### PR DESCRIPTION
**Pull request by nathancai97**
## Description

-- changed all references to signing up(button, css files, folders) to apply to onboard the switch to Auth0 from Okta. 

## Loom Video

https://www.loom.com/share/d329e5d231f34e1a9bc498c747cbfc7f

## Jira Ticket

https://bloomtechlabs.atlassian.net/browse/BL-864

## Type of change

- [x] Bug fix (non-breaking change which fixes an issue)

## Checklist:

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have removed unnecessary comments/console logs from my code
- [x] I have made corresponding changes to the documentation if necessary (optional)
- [x] My changes generate no new warnings
- [x] I have checked my code and corrected any misspellings
- [x] No duplicate code left within changed files
- [x] Size of pull request kept to a minimum
- [x] Pull request description clearly describes changes made & motivations for said changes

### CODE REVIEW

**Review by Charles-Merrill-Johnson — APPROVED** [review]
Pretty straightforward cleanup nice job! Also great job on the video very clear and concise!

**Review by CodyAskew9 — APPROVED** [review]

**Review by brimjustin — APPROVED** [review]
Nice job getting everything transitioned for flow!

**Review by stevenhastings — APPROVED** [review]
It's not the most fun work but, it is certainly necessary.  I have no qualms with this pull request.  Good job, Nathan. Keep up the solid work.

**Review by jack-semder — APPROVED** [review]
I like the vocab change, this looks and sounds much better!

**Pull request merged**
