### PR TITLE
Bug/calendar

### PR DESCRIPTION
**Pull request by ryansnorek**
## Description

The stakeholder has decided against using an in-app calendar and will instead utilize [Calendly](https://calendly.com/) to schedule meetings. We need to remove the Calendar component from the dashboard component and remove the calendar reducer so we only have one reducer.

[Videeo](https://www.loom.com/share/c7be8effd3f34bca9ac5cd31759245a5)

Contributors 
@Fvaldenegro95 

This PR was made including the latest and unmerged changes to redux from the `feature/redux-reorganizing` branch. The following additions include:
1. Removing the `Calendar` component from `SideBarComponents`
2. Removing the `CalendarComponent` file
3. Removing the calendar from redux actions/reducers

Fixes # [Trello card](https://trello.com/c/ommqSzVc)

## Type of change

- [x] Bug fix (non-breaking change which fixes an issue)

## Checklist:

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have removed unnecessary comments/console logs from my code
- [x] I have made corresponding changes to the documentation if necessary (optional)
- [x] My changes generate no new warnings
- [x] I have checked my code and corrected any misspellings
- [x] No duplicate code left within changed files
- [x] Size of pull request kept to a minimum
- [x] Pull request description clearly describes changes made & motivations for said changes

### CODE REVIEW

**Review by EnasELM — APPROVED** [review]
good, work

**Review by LmCastelli — APPROVED** [review]
Great description that highlights reasoning for changes, and clean changes made!

**Review by ST1414 — APPROVED** [review]

**Review by paulstgermain — CHANGES_REQUESTED** [review]
This PR needs a video walkthrough explaining and showcasing the changes made and reasoning for them! 😱

**Review by ErikBahena — APPROVED** [review]
You removed what was associated with the calendar. Looks good.

**Review by paulstgermain — APPROVED** [review]

**Pull request closed without merging**
