### PR TITLE
BL-471 Bug/welcome admin cursor styling

### PR DESCRIPTION
**Pull request by daaavit**
## Description

Welcome admin section was set to default I-beam cursor, fixed and replaced with pointer cursor.

#### Video Link

https://www.loom.com/share/1db951efe9b543d385b664e59df43843

#### Trello Link

https://trello.com/c/6mHp5hZq/420-fe-welcome-admin-on-over-shows-i-beam-cursor

## Type of change

- [x] Bug fix (non-breaking change which fixes an issue)

## Checklist:

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have removed unnecessary comments/console logs from my code
- [x] My changes generate no new warnings
- [x] I have checked my code and corrected any misspellings
- [x] No duplicate code left within changed files
- [x] Size of pull request kept to a minimum
- [x] Pull request description clearly describes changes made & motivations for said changes

### CODE REVIEW

**Review by roxanneweber — APPROVED** [review]
Great idea! This was a needed feature that is present on many other websites. Great work taking initiative.

**Review by ChristOscar — APPROVED** [review]
Thanks for taking an initiative on a small but useful feature. Everything followed the agile development cycle.

**Review by ethanrmiles — APPROVED** [review]
Great catch! Love your attention to detail

**Review by ambrojessica — APPROVED** [review]
Good fix! Small but very effective. The user will definitely appreciate it!

**Review by paulstgermain — APPROVED** [review]
Keep in mind that, while we want to keep PRs at a reasonable size, 1-3 line PRs are never necessary, and most companies will request that you don't submit PRs like this one unless a critical bug fix only took fixing 1 line!

A better method for these sorts of aesthetic changes would be to pursue tackling several aesthetic changes in a particular directory/section of the application and submitting them all together in one PR. This would also be worth more story points in the end, as the effort and forethought required would be greater!

**Pull request merged**
