### PR TITLE
Feature/official frontend auth0

### PR DESCRIPTION
**Pull request by williamvelichko**
## Description

Once user logs in or signups created the ability to grab the token from auth0 and set it into local storage. we need to set it into storage because in the axioswithauth we are able to grab the token from storage and send it into header. Okta had similar functionality.  refactored the logout in the dashboard that you logout with auth0 and also remove the token from local storage. Added a not permanent logout button because we have to finish with the private route.

#### contributors 

[https://github.com/aaronamendez](url)

#### Video Link

https://www.loom.com/share/2bcd60dc810e4ce195e7fd5344fa54f5

#### Trello Link

<blockquote class="trello-card"><a href="https:&#x2F;&#x2F;trello.com&#x2F;c&#x2F;8jaM7vF8&#x2F;377-auth0-add-auth0-login-and-signup-on-the-frontend">Auth0: add auth0 login and signup on the frontend</a></blockquote><script src="https://p.trellocdn.com/embed.min.js"></script>

___Please delete options that are not relevant.___

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] This change requires a documentation update

## Checklist:

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have removed unnecessary comments/console logs from my code
- [x] My changes generate no new warnings
- [x] I have checked my code and corrected any misspellings
- [x] No duplicate code left within changed files
- [x] Size of pull request kept to a minimum
- [x] Pull request description clearly describes changes made & motivations for said changes

### CODE REVIEW

**Review by oscy7 — APPROVED** [review]
Nicely done! Really exciting to see Auth0 do some heavy lifting! Making the local storage and tokens work is a job well done too!

**Review by quawilburn — APPROVED** [review]
Good job tackling getting auth0 hooked up on the frontend. I like how you kept this dry in your implementation.

**Review by minasoha — APPROVED** [review]
Great job on implementing Auth0 on the frontend.

**Review by clairelist — APPROVED** [review]
Approved! Excellent work getting this up and running.

**Comment by JoeyBertschler** [comment]
Well done. Glad we are transitioning to Auth0. While honestly not a fan of the style guides, our component approach makes it feasible -- and you did a great job keeping it clean considering the restrictions)

**Review by malloryshea — APPROVED** [review]
Nice job getting auth0 implemented. Code looks DRY & ready to go!

**Review by JoeyBertschler — COMMENTED** [review]
Well done. Glad we are transitioning to Auth0. While honestly not a fan of the style guides, our component approach makes it feasible -- and you did a great job keeping it clean considering the restrictions).

**Comment by paulstgermain** [comment]
Closing this PR and accounting for contributions on it as this work has been condensed into a new branch until breaking changes have been addressed.

**Pull request closed without merging**
