### PR TITLE
BL-269 Bug/navbar mobile resp

### PR DESCRIPTION
**Pull request by daaavit**
## Description

navbar was broken on mobile. added some media queries and fixed the navbar  responsiveness

#### Video Link

https://www.loom.com/share/842943da900a4c11971d2f33863f326b

#### Trello Link

https://trello.com/c/KNNtsTnH/413-navbar-is-not-responsive-on-mobile

## Type of change

___Please delete options that are not relevant.___

- [x] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)

## Checklist:

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have removed unnecessary comments/console logs from my code
- [x] My changes generate no new warnings
- [x] I have checked my code and corrected any misspellings
- [x] No duplicate code left within changed files
- [x] Size of pull request kept to a minimum
- [x] Pull request description clearly describes changes made & motivations for said changes

### CODE REVIEW

**Comment by paulstgermain** [comment]
2 Story Points!

**Review by ethanrmiles — CHANGES_REQUESTED** [review]
Your code looks great! It would helpful however if in your loom video you **showed** how these changes you made affect the product.

**Comment by daaavit** [comment]
> Your code looks great! It would helpful however if in your loom video you **showed** how these changes you made affect the product.

Hey, ethanrmiles I hope you were able to take a look at the loom video which was uploaded during commit time.
In loom recording, you can clearly see Navbar without media queries and with Media queries when I'm commenting/uncommenting the code.

**Comment by daaavit** [comment]
[Navbar is not responsive on mobile](https://trello.com/c/KNNtsTnH/413-navbar-is-not-responsive-on-mobile)

**Review by MingjunGeng — APPROVED** [review]
Very usefu

**Review by ethanrmiles — APPROVED** [review]
Looks great, thank you for the change!

**Review by joseph-fantuzzi — APPROVED** [review]
Good job @daaavit! Your loom video shows what the problem was before and after your code implementation. Mobile responsiveness is extremely important in web applications for a great mobile user experience. Great job reworking the navbar responsiveness and making it look more user-friendly and professional.

**Pull request merged**
