### PR TITLE
Mentor dashboard flushed out

### PR DESCRIPTION
**Pull request by taylorkangillescas**
## Description

Flushed out the basic framework for the mentor dashboard. We plan to implement components and routing shortly as well as the header, footer, and calendar. 

Quick note, branch names are incorrect... branch feature/MenteeDash corresponds to the mentor dashboard.

Trello: https://trello.com/c/D88NGYb4/45-as-a-mentor-upon-logging-in-id-like-to-have-the-dashboard-display-the-necessary-content-based-on-my-role

Loom: https://www.loom.com/share/2bbfb696dafa44988ef461d8648f36e1

## Type of change

Please delete options that are not relevant.

- [x] New feature (non-breaking change which adds functionality)

## Checklist:

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have removed unnecessary comments/console logs from my code
- [x] I have made corresponding changes to the documentation if necessary (optional)
- [x] My changes generate no new warnings
- [x] I have checked my code and corrected any misspellings
- [x] No duplicate code left within changed files
- [x] Size of pull request kept to a minimum
- [x] Pull request description clearly describes changes made & motivations for said changes

### CODE REVIEW

**Review by TrevourGuild — APPROVED** [review]
The dashboard looks great! I also like how it is specific to the mentor allowing them to view mentee progress and schedule meetings! Awesome job!

**Review by mariuscmoldovan — APPROVED** [review]
Nice work. A dedicated dashboard for the Mentor/Mentee is nice progress for the project.

**Review by VAIBHAVIBALAR — APPROVED** [review]
Great work people. The overall code looks clean and much well organized. Keep going

**Comment by JorshuaG** [comment]
This looks great, awesome seeing the bones of the dashboard being implemented. This is a good launching point to start getting components isolated and fleshed out. Great job.

**Pull request merged**
