### PR TITLE
Added Mentor edit form to wireframes

### PR DESCRIPTION
**Pull request by riqthedev**
Please delete options that are not relevant.

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] This change requires a documentation update

## Checklist:

- [ ] My code follows the style guidelines of this project
- [ ] I have performed a self-review of my own code
- [ ] I have removed unnecessary comments/console logs from my code
- [ ] I have made corresponding changes to the documentation if necessary (optional)
- [ ] My changes generate no new warnings
- [ ] I have checked my code and corrected any misspellings
- [ ] No duplicate code left within changed files
- [ ] Size of pull request kept to a minimum
- [ ] Pull request description clearly describes changes made & motivations for said changes

### CODE REVIEW

**Review by Cole-Richards — CHANGES_REQUESTED** [review]
From DS perspective:
The wire frame looks good! 
Fields I'd like to see changed to a drop down are the tech stack. We are going to be using this to match mentors to mentees and in order to do so we need a standard set of options that mentors can choose one or more of. Let me know if you need the options to choose from.

**Review by dankositzke — CHANGES_REQUESTED** [review]
Adding a text box where the mentor can drop a Calendly link would be great. This way mentees can easily schedule meetings with the mentor. If this is not the ideal process that were considering, then please let me know and we can adjust

**Review by Danielhk832 — CHANGES_REQUESTED** [review]
It appears as though you removed 25k lines from the package-lock.json file. I believe you forgot to run `npm install` before submitting this PR.

**Comment by riqthedev** [comment]
Appreciate the heads up! will fix

**Comment by ryan-hamblin** [comment]
Do we need wire frames in the code repository? Isn't there a better place to put them in a notion doc? Or maybe a link out to them from the Project's Readme.md?

**Pull request closed without merging**
