### PR TITLE
Clears all warnings from console and Change the naming of notes into memos

### PR DESCRIPTION
**Pull request by JCSime**
## Description

- Clears all warnings from console
- Change the naming from 'notes' into 'memos'

#### Video Link

[Loom Video] https://www.loom.com/share/c599f69bced7485790a8e28c88c70b27

#### Trello Link
https://trello.com/c/33cj6yxr

## Type of change

- [x] Bug fix (non-breaking change which fixes an issue)

## Checklist:

- [X] My code follows the style guidelines of this project
- [X] I have performed a self-review of my own code
- [X] I have removed unnecessary comments/console logs from my code
- [X] My changes generate no new warnings
- [X] I have checked my code and corrected any misspellings
- [X] No duplicate code left within changed files
- [X] Size of pull request kept to a minimum
- [X] Pull request description clearly describes changes made & motivations for said changes

### CODE REVIEW

**Review by Jmz0127 — APPROVED** [review]
I am a huge fan of updating code to give the user more context on functionality of the variable/function. another form of accessibility that is welcomed. good work!

**Comment by JoeyBertschler** [comment]
Was just about to type the same response as @Jmz0127. Well done

**Review by oscy7 — APPROVED** [review]
Great work on clearing the warnings. Attention to those details is important!

**Review by williamvelichko — APPROVED** [review]
great professionalism and great attention to detail!

**Review by sebas6292 — COMMENTED** [review]
Way to stay organize and avoid confusion. Clarity is always important! Good Job! Good looks clean.

**Review by JoeyBertschler — COMMENTED** [review]
Was just about to type the same response as @Jmz0127. Well done

**Pull request merged**
