### PR TITLE
Modified response data being returned from the database 

### PR DESCRIPTION
**Pull request by VABIII**
## Description

Modified response data being returned from the database so that all relevant information was in the proper format needed for the front end calendar. Connected modified response data to calendar component which now displays all meetings

#### Video Link

[Loom Video](https://www.loom.com/share/120986e44b99494592327388a9f988c8)

#### Trello Link

I'm not sure what happened to the trello card for this pull request, but it does not appear to be on the board anymore.

## Type of change

- [x] New feature (non-breaking change which adds functionality)

## Checklist:

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have removed unnecessary comments/console logs from my code
- [x] My changes generate no new warnings
- [x] I have checked my code and corrected any misspellings
- [x] No duplicate code left within changed files
- [x] Size of pull request kept to a minimum
- [x] Pull request description clearly describes changes made & motivations for said changes

### CODE REVIEW

**Review by oscy7 — APPROVED** [review]
Awesome job connecting the data and making all those functions! These changes are great improvements to the overall app!

**Review by quawilburn — APPROVED** [review]
Nice finesse getting the information back in a format that was needed, and getting the information displayed.

**Comment by clairelist** [comment]
Conflicts will need to be reviewed, but nice work getting this working!

**Review by clairelist — APPROVED** [review]

**Comment by JoeyBertschler** [comment]
Great react component! Personally not a fan of not leaving any comments and refactoring wherever possible, but I know we have to follow the style guides given. Under these circumstances, still as clean as could be. Nice :)

**Review by JoeyBertschler — COMMENTED** [review]
Great react component! Personally not a fan of not leaving any comments and refactoring wherever possible, but I know we have to follow the style guides given. Under these circumstances, still as clean as could be. Nice :)

**Pull request merged**
