### PR TITLE
Feature/update profile api calls

### PR DESCRIPTION
**Pull request by cyberkade**
## Description

As an Admin I'd like to be able to: 
 - find a user a consult its profile
 - edit profiles 
 - deactivate user accounts

This is the completion of a Trello card started by the previous team at Labs. The goal is to add requests to the form to complete the functionality of updating users as an admin, as well as address the slight UX changes suggested by Jason at the last stakeholder meeting.

## Type of change

- [x] New feature (non-breaking change which adds functionality)

## Checklist:

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have removed unnecessary comments/console logs from my code
- [x] My changes generate no new warnings
- [x] I have checked my code and corrected any misspellings
- [x] No duplicate code left within changed files
- [x] Size of pull request kept to a minimum
- [x] Pull request description clearly describes changes made & motivations for said changes

### Code
https://www.loom.com/share/c926837a9bc346af94fbd7348d008d56
### App
https://www.loom.com/share/e4bfaa2b1dea437a803cf9d122ee3a06

### Trello Card

https://trello.com/c/8SfgRWkz

## Co-Contributors
- Christopher Boyle

### CODE REVIEW

**Review by Tereamarie — APPROVED** [review]
Nice I was wondering if we needed to use an API call to the backend. looks great. also looks like this has branch conflicts might want  to check on that

**Comment by cyberkade** [comment]
> Nice I was wondering if we needed to use an API call to the backend. looks great. also looks like this has branch conflicts might want to check on that

Resolved it! Thanks for letting me know.

**Review by Retrofitt — APPROVED** [review]
Loom video was fantastic. the code looks great. functionality looks good. 
I appreciate the new file names, I think it creates a better understanding of what the component actually is, compared to the old name

Great work!

**Review by nhamilton1 — APPROVED** [review]
Great work, clean and concise!

**Review by rickmansfield — APPROVED** [review]
Really appreciate the fact you included the Trello card for this. Quite a few tasks knocked out here Axios, Get/ and PUT/ profiles API, clarifying the name, fully flushing the API call to deactivate, and clean up to boot. Very professional code Kade. Also, I notice the TODO. Someone will be lucky to have you on your team

**Review by teresafranxman97 — APPROVED** [review]
I like that you updated the naming convention this certainly allows for a much clearer understanding of what each component is meant to accomplish, thank you for implementing all of the API calls as well, that was a very important piece in order to communicate with the backend, great work!

**Pull request merged**
