### PR TITLE
Feature/Fix: application name fields split

### PR DESCRIPTION
**Pull request by kennedybryant**
## Description

[Loom Video](https://www.loom.com/share/992f7e5fa98f4f9d8da82f6fa1d8a887)

**First and last name fields in mentee and mentor application need to be created in place of 'name'.** 
The previous mentee and mentor applications had users enter their full name into one field. To give us more flexibility with the data that is collected from these applications, I changed both applications to require first and last name in separate fields.

Trello Card: [#93](https://trello.com/c/n79gU1en)

## Type of change

Please delete options that are not relevant.

- [x] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [x] This change requires a documentation update

## Checklist:

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have removed unnecessary comments/console logs from my code
- [x] My changes generate no new warnings
- [x] I have checked my code and corrected any misspellings
- [x] No duplicate code left within changed files
- [x] Size of pull request kept to a minimum
- [x] Pull request description clearly describes changes made & motivations for said changes

### CODE REVIEW

**Review by jimlemoine — APPROVED** [review]
Clear motivation for the change and a comprehensive update to the relevant files, it looks great running locally on my machine. One weird thing is that there are a large number of visual formatting changes for things like removing unnecessary space and changing double quotes to single quotes. It just makes me wonder if prettier is catching issues that a previous merge didn't catch for some reason.

**Comment by kennedybryant** [comment]
> 

You're exactly right, @jimlemoine. I ran into some formatting and merging issues while making this PR, but Paul suggested moving forward with it.

**Review by Danielhk832 — APPROVED** [review]
awesome work! Really appreciate the addition. It does appear that your linter has adjusted the formatting for a bunch of files, but I was still able to find your changes within. great job!

**Review by riqthedev — APPROVED** [review]
Great job kennedy. your code was easy to follow and very straightforward.

**Pull request merged**
