### PR TITLE
Feature/support-requests

### PR DESCRIPTION
**Pull request by amarrazza**
## Description

Created a component for Support Requests and implemented the UI using an Ant Design table and feeding it with dummy data. The next steps for this component would be linking it to an up and running endpoint from the backend.

#### Video Link

https://www.loom.com/share/4181fb40c344468c97b08853246e6193

#### Trello Link

https://trello.com/c/ZKVN5LlT/352-as-an-admin-i-want-to-view-support-requests-and-see-relevent-details-for-each

## Type of change

- [x] New feature (non-breaking change which adds functionality)

## Checklist:

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have removed unnecessary comments/console logs from my code
- [x] My changes generate no new warnings
- [x] I have checked my code and corrected any misspellings
- [x] No duplicate code left within changed files
- [x] Size of pull request kept to a minimum
- [x] Pull request description clearly describes changes made & motivations for said changes

### CODE REVIEW

**Review by oscy7 — APPROVED** [review]
Nice work! Adding that dummy data in definitely helps us understand what to do next and inches us closer to an even better app!

**Review by monicasalas86 — APPROVED** [review]
Love that function to sort by ticket number, date submitted, and by who requested it. Great feature to have!

**Comment by JoeyBertschler** [comment]
Dummy data & sorting are superb. Awesome job

**Review by JoeyBertschler — COMMENTED** [review]
Dummy data & sorting are superb. Awesome job. I have nothing else to add :)

**Pull request merged**
