### PR TITLE
Reuse component

### PR DESCRIPTION
**Pull request by johanna-rodriguez**
## Description

Please include a summary of the change and which issue is fixed. Please also include relevant motivation and context. List any dependencies that are required for this change.

Fixes # (issue)

## Type of change

Please delete options that are not relevant.

- [x] New feature (non-breaking change which adds functionality)

## Checklist:

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have removed unnecessary comments/console logs from my code
- [x] I have made corresponding changes to the documentation if necessary (optional)
- [x] My changes generate no new warnings
- [x] I have checked my code and corrected any misspellings
- [x] No duplicate code left within changed files
- [x] Size of pull request kept to a minimum
- [x] Pull request description clearly describes changes made & motivations for said changes
https://www.loom.com/share/c4c7543f37c9470789da2d565532322d
- Worked along with
@VAIBHAVIBALAR @kennymiesner @TrevourGuild @mariuscmoldovan @taylorkangillescas

### CODE REVIEW

**Review by VAIBHAVIBALAR — APPROVED** [review]
utils file is a great idea to prevent writing same code again and again. Clean code

**Review by JorshuaG — APPROVED** [review]
Always a good idea to make a component reusable if you can. Great job implementing that.

**Review by taylorkangillescas — APPROVED** [review]
Great job making the code reusable for future components.

**Review by tfbielawski — APPROVED** [review]
FYI: Lines 24 - 31 are commented out. If you change it, you can push again and it will fix it here automatically.

**Comment by johanna-rodriguez** [comment]
> FYI: Lines 24 - 31 are commented out. If you change it, you can push again and it will fix it here automatically.

I already did. You should look all the commits.

**Pull request merged**
