### PR TITLE
Fix/application axios calls

### PR DESCRIPTION
**Pull request by kennedybryant**
## Description

[Loom Video](https://www.loom.com/share/7ea50a596da644eaa73ec0726abc8636)

The purpose of this PR is to allow both mentors and mentees to submit their intake applications and potentially be signed up for an Okta account. I've worked closely with my backend team members Alan Waddell (@waddal) and Adam Krueng (@krueng), and this PR requires their branches feature/okta-auth and feature/okta-mentee-intake-database found in the [backend repo](https://github.com/BloomTech-Labs/underdog-devs-be-a). 

Trello Card [#126](https://trello.com/c/wGs9TCXJ)
## Type of change

Please delete options that are not relevant.

- [x] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [x] This change requires a documentation update

## Checklist:

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have removed unnecessary comments/console logs from my code
- [x] My changes generate no new warnings
- [x] I have checked my code and corrected any misspellings
- [x] No duplicate code left within changed files
- [x] Size of pull request kept to a minimum
- [x] Pull request description clearly describes changes made & motivations for said changes

### CODE REVIEW

**Review by addybeuch — APPROVED** [review]
Excellent catches on the calls. Now we can actually use those backend endpoints. Code is very clean and concise and will help future developers.

**Review by riqthedev — APPROVED** [review]
Very clear walkthrough of your code. Way to debug those bugs and help the endpoints run correctly.

**Review by Shane-Gray394 — APPROVED** [review]
Great job, and fantastic example of collaboration between front and back end.

**Review by Danielhk832 — APPROVED** [review]
love the video and the walkthrough of your changes! great stuff!

**Pull request merged**
