### PR TITLE
Adds Rick Mansfield profile and new section for addition contributors

### PR DESCRIPTION
**Pull request by rickmansfield**
## Description

This block adds Rick Mansfield's profile to the README.md and creates a template for additional contributors.

Fixes # (current team member Rick Mansfield not being credited) 

## README.md documentation update

- [ x] This change requires a documentation update

## Checklist:

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have removed unnecessary comments/console logs from my code
- [x] I have made corresponding changes to the documentation if necessary (optional)
- [x] My changes generate no new warnings
- [x] I have checked my code and corrected any misspellings
- [x] No duplicate code left within changed files
- [x] Size of pull request kept to a minimum
- [x] Pull request description clearly describes changes made & motivations for said changes

### CODE REVIEW

**Review by Retrofitt — APPROVED** [review]
## Code Feedback
Good job following the styles already existing when adding new contributors to the readme.md

**Comment by rickmansfield** [comment]
Fun easy README.md updates. Thanks to everyone for participating in this fun PR.

**Review by Tereamarie — APPROVED** [review]
Looks great and Professional easy to Read and Understand

**Review by cyberkade — APPROVED** [review]
Everybody's on here now, looks good! The 25,579 added files is spooky though.

**Pull request merged**
