### PR TITLE
Feature/urc account menu

### PR DESCRIPTION
**Pull request by phillipgalbraith**
## Description

We want to link to profile settings and logout through a dropdown from the profile info on the nav bar.  This is a natural place to look by industry standards.

#### Video Link

https://www.loom.com/share/0144a18c8b8b4faf98f30ad1949c6aff

#### Trello Link

As a user I can access logout in a predictable way and see updated notes by clicking in a typical area.

https://trello.com/c/uWpdnxkU

## Type of change

[X] New feature (non-breaking change which adds functionality)

## Checklist:

- [X] My code follows the style guidelines of this project
- [X] I have performed a self-review of my own code
- [X] I have removed unnecessary comments/console logs from my code
- [x] My changes generate no new warnings
- [X] I have checked my code and corrected any misspellings
- [X] No duplicate code left within changed files
- [X] Size of pull request kept to a minimum
- [X] Pull request description clearly describes changes made & motivations for said changes

### CODE REVIEW

**Review by acoman-cloud — APPROVED** [review]
Everything looks good. However I don't know why package-lock.json being deleted was added to this commit, for next time make sure to exclude it.

**Review by Astrospence — APPROVED** [review]
Your commit messages were well named, and I love that this pull request is scoped well and focused on a single feature.

**Review by areccus — APPROVED** [review]
Looks great, I think that most websites have it like this.

**Review by jcpcab — APPROVED** [review]
Great thinking adding such a common industry standard that could easily get looked over!

**Pull request merged**
