### PR TITLE
Feature/redux user

### PR DESCRIPTION
**Pull request by Jaredhall18**
## Description

Moved calls to get Okta id and user info into Redux so that they are accessible through global state.

Loom Link : https://www.loom.com/share/41c6923c03f24b33a43cc0c5d6927e4a

Trello card: https://trello.com/c/t9qdvrKh
This PR is building off of the previous PR made for Feature/redux dev #93

Specific changes:

### /state/actions/index
authenticateUser sets the user Id to state then dispatch get profile using that ID and setting the profile for that user to state.

1. Removed getRole from authenticateUser and added two .then statements.
- dispatched setUserId to set User Id from Okta to state.
- dispatched getProfile using that user Id to make a call to our backend to receive user info and setting it to state.

2. Add => Set_User_ID
3. Add => getProfile 

### /state/reducers/userReducer
1. Removed isFetching from Set_User_Info It is included in the Finally statement in AuthenticateUser

### src/config/index.js
1. Added a config folder that is holding the API-URL that is being pulled from process.env. 

## Contributors
@MrJacobSullivan
@ryansnorek 
@ST1414 (Sean Terry)

- [x] New feature (non-breaking change which adds functionality)

## Checklist:

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have removed unnecessary comments/console logs from my code
- [x] I have made corresponding changes to the documentation if necessary (optional)
- [x] My changes generate no new warnings
- [x] I have checked my code and corrected any misspellings
- [x] No duplicate code left within changed files
- [x] Size of pull request kept to a minimum
- [x] Pull request description clearly describes changes made & motivations for said changes

### CODE REVIEW

**Review by ryansnorek — APPROVED** [review]
This looks great. Nice and clear presentation.

**Review by EnasELM — APPROVED** [review]

**Comment by djho57** [comment]
All checks pass. Very informative video.

**Review by djho57 — APPROVED** [review]
All checks pass. Very informative video.

**Review by LmCastelli — APPROVED** [review]
Great addition for switching to Redux and having the user info available globally will be beneficial. Also the video explains the reasoning behind even minor tweaks, nicely done.

**Comment by JohnMBarnett** [comment]
Implementing redux here will definitely be very useful. Very concise video that clearly broke down the changes made.

**Review by JohnMBarnett — APPROVED** [review]
Implementing redux here will definitely be very useful. Very concise video that clearly broke down the changes made.

**Review by rdperry031 — APPROVED** [review]
Video was very informative. All checks pass. Everything looks good.

**Comment by ST1414** [comment]
Great walk through of the code changes in the video.  Code looks good. Well done.

**Pull request merged**
