### PR TITLE
Feature/mentee-app-validation

### PR DESCRIPTION
**Pull request by tinaxgao**
## Description

https://www.loom.com/share/69717f6d114348178054bb6debafa58c

This PR adds input validation to the mentee application form, to let applicants know if they haven't answered any questions that are required. It also adds a slash that was missing to the endpoint.

Fixes: 
- form input validation rules
- revise validation error messages
- added slash to endpoint URL

## Contributors
@benedictSchurwanz 
@tinaxgao

## Type of change

Please delete options that are not relevant.

- [x] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)

## Checklist:

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have removed unnecessary comments/console logs from my code
- [ ] I have made corresponding changes to the documentation if necessary (optional)
- [x] My changes generate no new warnings
- [x] I have checked my code and corrected any misspellings
- [x] No duplicate code left within changed files
- [x] Size of pull request kept to a minimum
- [x] Pull request description clearly describes changes made & motivations for said changes

### CODE REVIEW

**Comment by benedictSchurwanz** [comment]
There is a merge conflict in Mentee.js, I was having trouble resolving it, I'm submitting as is. I could use some help.

**Review by danielaescutia07 — APPROVED** [review]
This implementation will prevent improper data from being entered. Great effort!

**Review by JohnMBarnett — APPROVED** [review]
Looks great!

**Review by AnthonyMillerGit — COMMENTED** [review]
i like the way you handled edge cases here! great work!

**Pull request merged**
