### PR TITLE
Removed search bar from navbar at Stakeholder's request--there is no need for it.

### PR DESCRIPTION
**Pull request by tfbielawski**
## Description
The stakeholder said to remove the navbar because he could not see a use for it. I removed the navbar component from navbar.js and I removed the corresponding CSS code from navbar.css.  I listed it as a bug-fix because it is not a new feature, and it does not require documentation.

Fixes # (issue)
Removed unused component from code.

## Type of change

Please delete options that are not relevant.

- [x ] Bug fix (non-breaking change which fixes an issue)

## Checklist:

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have removed unnecessary comments/console logs from my code
- [x] I have made corresponding changes to the documentation if necessary (optional)
- [x] My changes generate no new warnings
- [x] I have checked my code and corrected any misspellings
- [x] No duplicate code left within changed files
- [x] Size of pull request kept to a minimum
- [x] Pull request description clearly describes changes made & motivations for said chang

https://user-images.githubusercontent.com/70349084/142031057-1dd7735b-e8a9-47e1-af90-17d5bd8b4da9.mp4

navbar
es

### CODE REVIEW

**Review by ChristopherHenao — APPROVED** [review]
The code looks good.

**Review by jessejohns-1 — APPROVED** [review]
Amazingly quick work. great job cleaning up the code and moving us forward for the stakeholder

**Review by gamboaldo — APPROVED** [review]
Great thing you were able to fulfill last week's request before tomorrows stakeholder meeting

**Review by mariuscmoldovan — APPROVED** [review]
Nice update,  requested by the stakeholder.

**Comment by johanna-rodriguez** [comment]
Great job removing unused component from code.

**Comment by Broveku** [comment]
Nice job aligning the code with the stakeholders vision and removing anything unnecessary

**Pull request merged**
