### PR TITLE
Bug/mentee signup not rendering

### PR DESCRIPTION
**Pull request by daaavit**
## Description

On the login page when we click on the signup button and try to sign up as a mentee, we were getting the error -> object is not iterable. now the error is fixed and Mentee can signup and fill the application

#### Video Link

https://www.loom.com/share/38ddf0ef6c9c4e22994863f2e90f9526

#### Trello Link

https://trello.com/c/DdHXijHe/419-mentee-cant-signup-fill-application-due-to-error

## Type of change

- [x] Bug fix (non-breaking change which fixes an issue)

## Checklist:

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have removed unnecessary comments/console logs from my code
- [x] My changes generate no new warnings
- [x] I have checked my code and corrected any misspellings
- [x] No duplicate code left within changed files
- [x] Size of pull request kept to a minimum
- [x] Pull request description clearly describes changes made & motivations for said changes

### CODE REVIEW

**Review by CodyAskew9 — APPROVED** [review]
Looks clean to me, good work!

**Review by joseph-fantuzzi — APPROVED** [review]
Good catch @daaavit! The loom video does a great job at explaining what the issue was and how you went about resolving it. This is a minor error, but definitely causing an issue and resulting in the page not rendering. Great job at catching what needed to be fixed to get the mentee signup page working!

**Review by ambrojessica — COMMENTED** [review]
I believe this bug/fix has already been merged to main. I worked on the mentee form myself and also saw the error so I made sure to change it to the proper syntax.

**Comment by paulstgermain** [comment]
This specific bugfix has already been merged to `main` - thus, I am closing this PR and attributing points for this to all engineers and reviewers involved here.

**Pull request closed without merging**
