### PR TITLE
added wireframes landing-page

### PR DESCRIPTION
**Pull request by ylei1088**
## Description
- landing-page wireframes (desktop and mobile)
- created design system for wireframes and prototypes
- created new Figma file for wireframes design -[link](https://www.figma.com/file/cwOoFddP7i0BdcP1oB7Kco/Underdog-Devs-Ant-Design)
- [wireframes walkthrough](https://www.loom.com/share/8fea964bb5d74a4ba27dd004632f1e7c?sharedAppSource=personal_library)

Fixes # (issue)
- landing page introduction of underdog-devs

## Type of change

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] This change requires a documentation update

## Checklist:

- [ ] My code follows the style guidelines of this project
- [ ] I have performed a self-review of my own code
- [ ] I have removed unnecessary comments/console logs from my code
- [ ] I have made corresponding changes to the documentation if necessary (optional)
- [ ] My changes generate no new warnings
- [ ] I have checked my code and corrected any misspellings
- [ ] No duplicate code left within changed files
- [x] Size of pull request kept to a minimum
- [x] Pull request description clearly describes changes made & motivations for said changes

### CODE REVIEW

**Review by addybeuch — APPROVED** [review]
Very great job on these wireframes. I like the simple and clean approach as well as the collapsible text in the mobile version. They may ask you to make a short Loom video.

**Review by kennedybryant — CHANGES_REQUESTED** [review]
Perhaps it's just me, but I wasn't getting any sound from your loom video! I would love to hear you walk us through your work. At a glance, your wireframes for the landing page look great. My only concern is that they don't quite match wireframes of pages that have already been produced. For example, is the navigation bar placed at the top of the landing page on purpose, whereas the nav bar is on the left in our current pages.

**Review by jimlemoine — APPROVED** [review]
Excellent work on the landing page wireframes, I think the client and visitors will agree it is great looking and will be easy to use. I wouldn't be surprised if the client ends up wanting the entire user-facing product to include some of this design as well.

**Review by Danielhk832 — APPROVED** [review]
Awesome work Vicki, love the mobile view. I think it really gives the site a modern feel.

**Review by johnfigs — APPROVED** [review]
The wireframes look great. It will make the site more intuitive and easier to navigate while upgrading the aesthetic.

**Review by krueng — APPROVED** [review]
Looks amazing, love the implementation of your design here. Great work!
Always love your design. excited to see the next one :)

**Review by kennedybryant — APPROVED** [review]

**Pull request merged**
