### PR TITLE
Welcome message

### PR DESCRIPTION
**Pull request by maidiance**
## Description

As a logged in user, the Login and Apply buttons on the Landing page should not display and instead there should be a welcome message.

#### Video Link

[Loom Video](https://www.loom.com/share/988fdb62333640cf967aa388fd3b10b0)

#### Trello Link

<blockquote class="trello-card"><a href="https://trello.com/c/7SJ5bfWf/284-as-a-logged-in-user-i-want-to-see-welcome-username-instead-of-login-and-apply-buttons-in-the-landing-page">As a logged in user, I want to see Welcome <username> instead of Login and Apply buttons in the Landing page.</a></blockquote>

## Type of change

- [✔️] Bug fix (non-breaking change which fixes an issue)

## Checklist:

- [✔️] My code follows the style guidelines of this project
- [✔️] I have performed a self-review of my own code
- [✔️] I have removed unnecessary comments/console logs from my code
- [✔️] My changes generate no new warnings
- [✔️] I have checked my code and corrected any misspellings
- [✔️] No duplicate code left within changed files
- [✔️] Size of pull request kept to a minimum
- [✔️] Pull request description clearly describes changes made & motivations for said changes

### CODE REVIEW

**Review by wscottreynders — APPROVED** [review]
A nice addition to the user experience. It makes applications more enjoyable to use when we feel like they like us. This adds a nice human touch.

**Review by adamhinton — APPROVED** [review]
Always love a human touch when I'm visiting a website. It's not all code and APIs.

**Review by itsmerobert12 — APPROVED** [review]
I really like how this user experience shows. It feels a lot more "known" as having a human vibe behind it makes it all that much better.

**Comment by areccus** [comment]
The addition of the welcome message, makes it feel more like a community and not just an organization. These are small details that shouldn't be ignored.

**Review by OrdainedRat — APPROVED** [review]
This looks really nice. Keep it up!

**Review by areccus — APPROVED** [review]

**Pull request merged**
