### PR TITLE
Feature/update profile

### PR DESCRIPTION
**Pull request by RaphaelHebert**
## Description

Please include a summary of the change and which issue is fixed. Please also include relevant motivation and context. List any dependencies that are required for this change.

Fixes # (issue)

## Type of change

Please delete options that are not relevant.

- [ ] Bug fix (non-breaking change which fixes an issue)
- [X] New feature (non-breaking change which adds functionality)
- [ ] This change requires a documentation update

## Checklist:

- [X] My code follows the style guidelines of this project
- [ ] I have performed a self-review of my own code
- [X] I have removed unnecessary comments/console logs from my code
- [ ] I have made corresponding changes to the documentation if necessary (optional)
- [X] My changes generate no new warnings
- [X] I have checked my code and corrected any misspellings
- [X] No duplicate code left within changed files
- [X] Size of pull request kept to a minimum
- [X] Pull request description clearly describes changes made & motivations for said changes

<a href="https://www.loom.com/share/484337c17c054c049f843751abed6231">
    <p>Comparing main...Feature/update-profile · BloomTech-Labs/underdog-devs-fe-a - Watch Video</p>
    
  </a>

### CODE REVIEW

**Comment by nhamilton1** [comment]
Well done! The loom video was extremely helpful to understand the implementations.

**Review by nhamilton1 — COMMENTED** [review]
Well done! The loom video was extremely helpful to understand the implementations.

**Review by rickmansfield — APPROVED** [review]
Excellent work. The model will ensure the user is "certain" before deleting.

**Review by cyberkade — APPROVED** [review]
Great Loom video, clean code!

**Pull request merged**
