### PR TITLE
Feature/sidebar

### PR DESCRIPTION
**Pull request by Retrofitt**
## Co-Authors

Co-authored-by: 
Nicholas Hamilton <nickh3592@gmail.com>
Richard Oh <n24512@protonmail.com>
Teresa Franxman <teresafranxman97@gmail.com>

## Description

New Feature, Sidebar. This PR addresses Trello card #77 "As a user I want an initial framework sidebar navigation system to access all appropriate features.". Sidebar was appropriately implemented as well as code in place for components to be displayed & code in place for appropriate buttons to be available and displayed to the correct role_id.

Co-Author

## Type of change

- [x] New feature (non-breaking change which adds functionality)

## Checklist:

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have removed unnecessary comments/console logs from my code
- [x] I have made corresponding changes to the documentation if necessary (optional)
- [x] My changes generate no new warnings
- [x] I have checked my code and corrected any misspellings
- [x] No duplicate code left within changed files
- [x] Size of pull request kept to a minimum
- [x] Pull request description clearly describes changes made & motivations for said changes

## Loom Video
<https://www.loom.com/share/001cf1d964a14e27b93b66fbb0c27f00>

### CODE REVIEW

**Review by Chris-Boyle-94 — CHANGES_REQUESTED** [review]
It looks like there are some linting errors involving unused imports and variables on a few of these files, otherwise looks great

**Review by nhamilton1 — APPROVED** [review]
Everything looks great, just userInfo is not being used, we can just remove it next time. Other than that, I am excited to add some more functionality to this!

**Review by Chris-Boyle-94 — APPROVED** [review]

**Review by cyberkade — APPROVED** [review]
Perfect, this is exactly what we need. Let's get this merged ASAP.

**Review by nhamilton1 — APPROVED** [review]

**Review by paulstgermain — APPROVED** [review]
## PR Walkthrough Review

This was a fantastic walkthrough, and exactly what I'm looking to get out of these Loom recordings! You spoke through your work proficiently, and the extra steps you took to showcase your changes in action through your `localhost` added a lot to your representation of your work. This is exactly how you should talk through your work in any upcoming interviews and in your future career!

## Code Review

The code itself is exactly as professionally implemented. You and your team did a great job implementing the sidebar feature, and I appreciate the extra steps you all took to also clean up some of the surrounding components and implementation while you were there, like the `HomeContainer.js` file!

Clean, well-formatted code that brings a sorely needed feature to our app - this is an easy approval!

**Pull request merged**
