### PR TITLE
BL-274 feature/add-reply

### PR DESCRIPTION
**Pull request by mgabon**
## Description

Reply functionality improvements, updating CSS media queries and starting the process of replies being shown on the page.

#### Trello Link

<blockquote class="trello-card"><a href="https://trello.com/c/eOPWgjvA/323-as-a-user-i-would-like-to-be-able-to-add-a-reply-functionality-in-the-memo-in-order-for-the-user-to-respond-or-add-any-additiona">Feature: Add a reply to a memo as a user.</a></blockquote>

### Loom Video
<blockquote class="trello-card"><a href="https://www.loom.com/share/d115570109844ef7b22f285d05f90ed4
">video link</a></blockquote>

## Type of change

- [x] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)

## Checklist:

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have removed unnecessary comments/console logs from my code
- [x] My changes generate no new warnings
- [x] I have checked my code and corrected any misspellings
- [x] No duplicate code left within changed files
- [x] Size of pull request kept to a minimum
- [x] Pull request description clearly describes changes made & motivations for said changes

### CODE REVIEW

**Comment by andrejohnson** [comment]
I saw that the side menu had a transition animation whenever the screen size was reduced, also the text field had the input text color in white so I made a change to the text color. I made a change to the replay.css file that added a media query that will reduce the reply field size to fit the new resolution. there is no change for reply on smaller screen sizes

**Comment by andrejohnson** [comment]
https://www.loom.com/share/d115570109844ef7b22f285d05f90ed4

**Review by daaavit — APPROVED** [review]
great job for adding responsiveness

**Review by rogerfvieira — COMMENTED** [review]
Good spot with the white text issue in the input field!

**Pull request merged**
