### PR TITLE
BL-146 Show commend work

### PR DESCRIPTION
**Pull request by MingjunGeng**
## Description

In this update, I add  show replied comments in src/components/common/MemosTable/AddReply/showReply.js
Need to use backend [underdog-devs-be-a #129](https://github.com/BloomTech-Labs/underdog-devs-be-a/pull/129) refactor/user-response branch as there is comment table in it

#### Video Link

https://loom.com/share/73a2c22f09064c7b9ed7c05c24b8c5aa

#### Trello Link

https://trello.com/c/eOPWgjvA/323-as-a-user-i-would-like-to-be-able-to-add-a-reply-functionality-in-the-memo-in-order-for-the-user-to-respond-or-add-any-additiona

## Type of change

___Please delete options that are not relevant.___

- [x] New feature (non-breaking change which adds functionality)

## Checklist:

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have removed unnecessary comments/console logs from my code
- [x] My changes generate no new warnings
- [x] I have checked my code and corrected any misspellings
- [x] No duplicate code left within changed files
- [x] Size of pull request kept to a minimum
- [x] Pull request description clearly describes changes made & motivations for said changes

### CODE REVIEW

**Comment by Kseniyapl** [comment]
I think you have a merge issue because you didn't pull the latest version. You need to run git pull origin main before pushing any new changes.

**Review by FftyShadesofCode — CHANGES_REQUESTED** [review]
I agree with Ksinya. While your code looks great, the issue of not being on the most recent code is the setback. I would request that you pull the most recent code, make sure there are no conflicts, and then resubmit?

**Comment by MingjunGeng** [comment]
Description
In this update, I changed the style of replying to comments using ant design.
I modified :src/components/common/MemosTable/AddReply/showReply.js

Video Link:
https://www.loom.com/share/8b105397214640e2a8a7e53f728ba2fe

**Review by daaavit — APPROVED** [review]
great job using ant design instead of custom styling. I like the way you implement react hooks. please make sure clean {' '}  <- any comment/uncomment marks before pushing. Overall excellent jobs.

**Review by MingjunGeng — COMMENTED** [review]
already delete unused variables

**Review by tvolchko — APPROVED** [review]

**Review by ethanrmiles — DISMISSED** [review]
Great implementation of the reply feature, and excellent job making changes to code as needed!

**Review by andrejohnson — DISMISSED** [review]
this was needed for a while good job

**Pull request merged**
