### PR TITLE
Bug/Mentee Intake Form not storing inputed values in form state

### PR DESCRIPTION
**Pull request by benedictSchurwanz**
## Description

This corrects bugs preventing saving user input to form state, refactors the useForms hook and adds functionality to it. 

#### Video Link

[Loom Video](https://www.loom.com/share/2f8ccde7fbd24cc4a5579c6cc720ac22)

#### Trello Link

https://trello.com/c/qxmFY78Q

## Type of change

- [x] Bug fix (non-breaking change which fixes an issue)
- [x] This change requires a documentation update

## Checklist:

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have removed unnecessary comments/console logs from my code
- [x] My changes generate no new warnings
- [x] I have checked my code and corrected any misspellings
- [x] No duplicate code left within changed files
- [x] Size of pull request kept to a minimum
- [x] Pull request description clearly describes changes made & motivations for said changes

### CODE REVIEW

**Review by VABIII — APPROVED** [review]
Good job with the onChanges. Looks good.

**Comment by benedictSchurwanz** [comment]
[Bug: Mentee Intake form submit: rewrite useForms hook, inputs in Mentee intake form](https://trello.com/c/qxmFY78Q/331-bug-mentee-intake-form-submit-rewrite-useforms-hook-inputs-in-mentee-intake-form)

**Comment by benedictSchurwanz** [comment]
I added the last three commits just now, because I realized my changes to the useForms hook broke two other files which used useForms:
src/components/pages/RoleSignup/Applications/Mentor.js and
src/components/pages/ManageResources/RenderResourceManagement.js

**Comment by benedictSchurwanz** [comment]
[Bug: Mentor Intake form state](https://trello.com/c/U49ZSp1O/365-bug-mentor-intake-form-state)

**Pull request closed without merging**
