### PR TITLE
Feature/dashboard placeholder in sidebar

### PR DESCRIPTION
**Pull request by jimlemoine**
## Description
PR VIDEO https://www.loom.com/share/7b1c33942d1346998166cfaf559e23ee
My team is building a new dashboard view to give admins a high level overview of tickets (applications, resource requests, escalations, meetings) that are relevant to the admin. This PR simply includes the addition of a dashboard link in the lefthand sidebar navigation panel with placeholder text so that we can build the dashboard component next.

Fix co-authored by Seth Blakley sethblakley869@gmail.com

Adds dashboard to sidenav per task in Trello ticket  #114 https://trello.com/c/8GIwnj92

## Type of change

- [X] New feature (non-breaking change which adds functionality)

## Checklist:

- [X] My code follows the style guidelines of this project
- [X] I have performed a self-review of my own code
- [X] I have removed unnecessary comments/console logs from my code
- [X] My changes generate no new warnings
- [X] I have checked my code and corrected any misspellings
- [X] No duplicate code left within changed files
- [X] Size of pull request kept to a minimum
- [X] Pull request description clearly describes changes made & motivations for said changes

### CODE REVIEW

**Review by krueng — APPROVED** [review]
Your code and video were excellent. They make it easier to decipher what those components were intended for and your explanation greatly simplified it.

**Review by johnfigs — APPROVED** [review]
Video explains the nature of these changes and why they are being made. This is setting the team up to tackle future issues. Approving this request.

**Review by kennedybryant — APPROVED** [review]
Nice job adding a the dashboard link. I had some difficulties understanding how to get a component properly linked in the beginning, and that was with the placeholder already present. This PR and video will be a great tool for future developers (including myself) when adding other components to our navigation sidebar.

**Comment by riqthedev** [comment]
Your code was very easy to follow along with. especially since you showed the wireframe you were working on in the design critique I can see how you can implement the idea.

**Review by riqthedev — APPROVED** [review]
Your code was very easy to follow along with. especially since you showed the wireframe you were working on in the design critique I can see how you can implement the idea.

**Pull request merged**
