### PR TITLE
fixed styling for mentee-mentor sign up page

### PR DESCRIPTION
**Pull request by daaavit**
## Description

when we click on sign up> Mentee/Mentor: users had a hard time reading labels for input fields so issue is fixed and ready for production
#### Video Link

https://www.loom.com/share/e3cc6c42390b40a0a93e336340f7a51a

#### Jira Link

https://trello.com/b/VcLLXM9l/underdog-devs-resource-manager

☑︎ Bug fix (non-breaking change which fixes an issue)

## Checklist:

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have removed unnecessary comments/console logs from my code
- [x] My changes generate no new warnings
- [x] I have checked my code and corrected any misspellings
- [x] No duplicate code left within changed files
- [x] Size of pull request kept to a minimum
- [x] Pull request description clearly describes changes made & motivations for said changes

### CODE REVIEW

**Review by paulstgermain — CHANGES_REQUESTED** [review]
@daaavit We need to be making tickets in Jira, not Trello - we should also largely be pulling tasks from the backlog/ready for work section in Jira and, if a new ticket is necessary, letting our RMs know so that they can scope and score the tickets appropriately.

Please create a new ticket for this on Jira and properly connect this PR to that ticket by following the following steps:

1. Open our project's "Backlog" page and scroll to the bottom of that view.
2. Click "Create Issue", and fill the ticket out with the title and detail from Trello.
3. Note the ticket ID (BL-123, for example.)
4. Come back to this PR, and rename the PR title from "fixed styling for mentee-mentor sign up page" to **"BL-XXX fixed styling for mentee-mentor sign up page**.

**Comment by daaavit** [comment]
> @daaavit We need to be making tickets in Jira, not Trello - we should also largely be pulling tasks from the backlog/ready for work section in Jira and, if a new ticket is necessary, letting our RMs know so that they can scope and score the tickets appropriately.
> 
> Please create a new ticket for this on Jira and properly connect this PR to that ticket by following the following steps:
> 
> 1. Open our project's "Backlog" page and scroll to the bottom of that view.
> 2. Click "Create Issue", and fill the ticket out with the title and detail from Trello.
> 3. Note the ticket ID (BL-123, for example.)
> 4. Come back to this PR, and rename the PR title from "fixed styling for mentee-mentor sign up page" to **"BL-XXX fixed styling for mentee-mentor sign up page**.


I'm not able to open the issue I don't have a permission to do that that's why opening on trello 
Screen Shot 2022-06-24 at 17 16 03

**Review by ivanovicuros — APPROVED** [review]

**Review by ethanrmiles — APPROVED** [review]
Great catch!

**Comment by andrejohnson** [comment]
wow i never noticed this before good save

**Review by andrejohnson — APPROVED** [review]
wow i never noticed this before good save

**Review by miguelaledesma — APPROVED** [review]
Nice catch and easy fix! All that is left is for you to fix the changes that Paul suggested.

**Pull request closed without merging**
