### PR TITLE
Style/signup

### PR DESCRIPTION
**Pull request by tristanharrower**
https://www.loom.com/share/871cf0a1a1f043d3a50b9a4f554c21a4

## Description

I created a new branch to include better responsiveness on the Signup.js form.  It seems there was a media query that made the pictures super big under 880 px width.   I converted that to look better and also removed unnecessary styling to be more concise for future developers.

## Contributors 
@danielaescutia07 

Fixes # (issue)

responsiveness for the Signup.js page and removed unnecessary styling.

## Type of change

Please delete options that are not relevant.

- [x ] Bug fix (non-breaking change which fixes an issue)
- [ x] New feature (non-breaking change which adds functionality)
- [x ] This change requires a documentation update

## Checklist:

- [ x] My code follows the style guidelines of this project
- [x ] I have performed a self-review of my own code
- [x ] I have removed unnecessary comments/console logs from my code
- [x ] I have made corresponding changes to the documentation if necessary (optional)
- [x ] My changes generate no new warnings
- [x ] I have checked my code and corrected any misspellings
- [x ] No duplicate code left within changed files
- [x ] Size of pull request kept to a minimum
- [x ] Pull request description clearly describes changes made & motivations for said changes

### CODE REVIEW

**Review by AnthonyMillerGit — COMMENTED** [review]
great catch on the responsiveness bug!

**Comment by Fvaldenegro95** [comment]
Definitely a needed change! Looks great!

**Review by Fvaldenegro95 — APPROVED** [review]
Definitely a needed change! Good work!

**Review by djho57 — APPROVED** [review]
Good change/fix. Always love more accessibility. Video was easy to follow as well!

**Review by r-gio28 — APPROVED** [review]
Great changes for a responsive and accessible web interface.

**Pull request merged**
