### PR TITLE
Feature/application styling

### PR DESCRIPTION
**Pull request by teresafranxman97**
When a user initially landed on the signup page they were met with a very basic layout that did not contain a way for a user to be able to navigate around. Our new implementation now gives users the functionality to freely navigate between the login, signup, and Mentor / Mentee application forms. 

*** Loom video link: https://www.loom.com/share/0c42ed343f3747bea9f5e6e4fddd0265 ***

Fixes # (98)

## Type of change
- [x] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)

## Checklist:

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have removed unnecessary comments/console logs from my code
- [x] I have made corresponding changes to the documentation if necessary (optional)
- [x] My changes generate no new warnings
- [x] I have checked my code and corrected any misspellings
- [x] No duplicate code left within changed files
- [x] Size of pull request kept to a minimum
- [x] Pull request description clearly describes changes made & motivations for said changes

### CODE REVIEW

**Review by ayv8er — APPROVED** [review]
Loving the breadcrumbs feature from Ant Design being implemented!

**Review by Tereamarie — APPROVED** [review]
Excellent Loom video your explanation was great. you may need to speak up just a little bit louder other than that great work.  Your placeholders look good your code is easy to read and understand very dry code awsome job Teresa.

**Review by Pluviio — APPROVED** [review]
I like to see whats being done here using ant design. Seems to add another layer of creativity and design.

**Comment by RaphaelHebert** [comment]
Great use of antDesign! The code is clear, easy to read and understand.

**Review by RaphaelHebert — APPROVED** [review]
Great use of antDesign! The code is clear, easy to read and understand.

**Pull request merged**
