### PR TITLE
Updated footer styling

### PR DESCRIPTION
**Pull request by iwood55**
## Description

Changed the footer styling.

## Checklist:

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have removed unnecessary comments/console logs from my code
- [x] I have made corresponding changes to the documentation if necessary (optional)
- [x] My changes generate no new warnings
- [x] I have checked my code and corrected any misspellings
- [x] No duplicate code left within changed files
- [x] Size of pull request kept to a minimum
- [x] Pull request description clearly describes changes made & motivations for said changes

https://user-images.githubusercontent.com/81526595/142518410-b0cb0022-7c25-4e1b-bbbd-cda62c69e2d8.mp4

### CODE REVIEW

**Review by johanna-rodriguez — APPROVED** [review]
Nice job improving the footer styling.

**Review by Broveku — APPROVED** [review]
Nice job getting the footer squared away!

**Comment by nhamilton1** [comment]
This looks great! This also fixes the mentee and mentor signup page where they would be behind the footer.

**Review by nhamilton1 — COMMENTED** [review]
This looks great! This also fixes the mentee and mentor signup page where they would be behind the footer.

**Review by rickmansfield — COMMENTED** [review]
Excellent fix. Looks good. I did notice in line 75 there is no final return. This is super nit-picky. But I recall Warren in our code reviews said this was the "standard"?

**Review by cyberkade — APPROVED** [review]
Great changes to the footer! Looks ready to merge.

**Review by nhamilton1 — APPROVED** [review]

**Pull request merged**
